project:
  type: website
  output-dir: docs

website:
  title: "Cuaderno técnico"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: articulos/index.qmd
        text: Artículos
      - href: apuntes/index.qmd
        text: Apuntes
      - href: clases/index.qmd
        text: Clases
      - href: proyectos/index.qmd
        text: Proyectos
      - href: sobre-mi.qmd
        text: Sobre mí
  search: true
  page-footer:
    left: "© René Quezada"
    right: "Hecho con Quarto"

format:
  html:
    theme:
      - sandstone
      - styles-sandstone.scss
    toc: true
    toc-location: right
    smooth-scroll: true
    include-after-body: _includes/notes-prev-next.html

filters:
  - _extensions/custom/back-to-section.lua