<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Efectos globales, jerarquía, valores a priori, MCMC y valor a posteriori predictivo explicados desde la ecuación hasta el código.">

<title>5. Inferencia Bayesiana con PyMC – NerdyMiner</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-b16add4d910ff6038463ffc00184b1c1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-e3b8bbca183a7d6761657ecb5c5aa65f.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-b16add4d910ff6038463ffc00184b1c1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-20a3660c41a27997b0067576444d6464.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-82b8a8f05674b84d57516846be433586.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-20a3660c41a27997b0067576444d6464.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../images/nerdyminer-icon.svg" alt="NerdyMiner" class="navbar-logo light-content">
    <img src="../../images/nerdyminer-icon.svg" alt="NerdyMiner" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">NerdyMiner</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../articulos/index.html"> 
<span class="menu-text">Artículos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../apuntes/index.html"> 
<span class="menu-text">Apuntes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../clases/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../bibliografia.html"> 
<span class="menu-text">Bibliografía</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../proyectos/index.html"> 
<span class="menu-text">Proyectos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../licencia.html"> 
<span class="menu-text">Licencia</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../sobre-mi.html"> 
<span class="menu-text">Sobre mí</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#por-qué-modelar-una-distribución-y-no-sólo-un-punto" id="toc-por-qué-modelar-una-distribución-y-no-sólo-un-punto" class="nav-link active" data-scroll-target="#por-qué-modelar-una-distribución-y-no-sólo-un-punto">¿Por qué modelar una distribución y no sólo un punto?</a></li>
  <li><a href="#modelo-jerárquico-de-efectos-globales" id="toc-modelo-jerárquico-de-efectos-globales" class="nav-link" data-scroll-target="#modelo-jerárquico-de-efectos-globales">Modelo jerárquico de efectos globales</a></li>
  <li><a href="#identificabilidad-del-parámetro-de-sesgo-y-las-firmas-geológicas" id="toc-identificabilidad-del-parámetro-de-sesgo-y-las-firmas-geológicas" class="nav-link" data-scroll-target="#identificabilidad-del-parámetro-de-sesgo-y-las-firmas-geológicas">Identificabilidad del parámetro de sesgo y las firmas geológicas</a></li>
  <li><a href="#agrupamiento-parcial-para-variables-de-procedencia-y-dureza-insitu" id="toc-agrupamiento-parcial-para-variables-de-procedencia-y-dureza-insitu" class="nav-link" data-scroll-target="#agrupamiento-parcial-para-variables-de-procedencia-y-dureza-insitu">Agrupamiento parcial para variables de procedencia y dureza in–situ</a></li>
  <li><a href="#valores-a-priori-empíricos-para-efectos-regulares" id="toc-valores-a-priori-empíricos-para-efectos-regulares" class="nav-link" data-scroll-target="#valores-a-priori-empíricos-para-efectos-regulares">Valores a priori empíricos para efectos regulares</a></li>
  <li><a href="#diseño-del-modelo-bayesiano-en-pymc" id="toc-diseño-del-modelo-bayesiano-en-pymc" class="nav-link" data-scroll-target="#diseño-del-modelo-bayesiano-en-pymc">Diseño del modelo Bayesiano en <font color="darkmagenta">PyMC</font></a></li>
  <li><a href="#técnica-de-muestreo-sin-giros-en-u-nuts" id="toc-técnica-de-muestreo-sin-giros-en-u-nuts" class="nav-link" data-scroll-target="#técnica-de-muestreo-sin-giros-en-u-nuts">Técnica de muestreo sin giros en U (NUTS)</a></li>
  <li><a href="#formato-de-salida-del-modelo-media-a-posteriori-versus-predictibilidad" id="toc-formato-de-salida-del-modelo-media-a-posteriori-versus-predictibilidad" class="nav-link" data-scroll-target="#formato-de-salida-del-modelo-media-a-posteriori-versus-predictibilidad">Formato de salida del modelo: Media a posteriori versus predictibilidad</a></li>
  <li><a href="#procedimiento-de-backtesting" id="toc-procedimiento-de-backtesting" class="nav-link" data-scroll-target="#procedimiento-de-backtesting">Procedimiento de <em>backtesting</em></a></li>
  <li><a href="#auditabilidad-de-la-inferencia-bayesiana" id="toc-auditabilidad-de-la-inferencia-bayesiana" class="nav-link" data-scroll-target="#auditabilidad-de-la-inferencia-bayesiana">Auditabilidad de la inferencia Bayesiana</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">5. Inferencia Bayesiana con <font color="darkmagenta">PyMC</font></h1>
</div>

<div>
  <div class="description">
    Efectos globales, jerarquía, valores a priori, MCMC y valor a posteriori predictivo explicados desde la ecuación hasta el código.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><a href="../../proyectos/bayesian-tph-forecasting/index.html">← Volver al proyecto</a></p>
<section id="por-qué-modelar-una-distribución-y-no-sólo-un-punto" class="level2">
<h2 class="anchored" data-anchor-id="por-qué-modelar-una-distribución-y-no-sólo-un-punto">¿Por qué modelar una distribución y no sólo un punto?</h2>
<p>Nuestro diseño de producto final es un gráfico como el que se muestra en la <a href="#fig-idea" class="quarto-xref">Figura&nbsp;1</a>.</p>
<div id="fig-idea" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-idea-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="assets/bridge_idea.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-idea-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Idea inicial que representa el producto al que deseamos llegar: Un gráfico de cascada que permite estimar las contribuciones positivas y negativas de tratamiento respecto de una base contextual, un valor esperado y el tratamiento observado, con el propósito de intentar aislar el efecto operacional de aquel que depende de las condiciones del mineral y la planta
</figcaption>
</figure>
</div>
<p>El gráfico de cascada permite a un ingeniero de planta ver qué parte del tratamiento observado se explica por la firma geológica de la alimentación, la procedencia del mineral y su dureza, y qué parte depende de las condiciones operacionales. La base contextual que define la primera barra del gráfico corresponde a la media esperada para un determinado período de tiempo (con granularidad diaria), y se calcula a partir del muestreo realizado sobre la distribución a posteriori de la media de tratamiento. Las contribuciones de cada variable se calculan conforme un modelo de regresión lineal que permite estimar parámetros a priori para cada una de las variables contextuales que deseamos incluir en el modelo. La barra final del gráfico corresponde al tratamiento observado, y la diferencia entre esta barra y la base contextual nos permite aislar el efecto operacional.</p>
<p>Esta representación desacoplada del tratamiento, por definición, requiere de una referencia contextual, pero también debe ser capaz de distinguir entre dos afirmaciones:</p>
<ul>
<li><em>La media esperada de tratamiento, para este contexto, es cercana a los 2230 tph</em>.</li>
<li><em>El próximo día observado “debiera” caer cerca de los 2230 tph</em>.</li>
</ul>
<p>La segunda afirmación incluye la incertidumbre sobre la media <strong>más</strong> la variabilidad diaria que el contexto no captura. Un modelo Bayesiano conserva ambas fuentes como distribuciones y permite regularizar familias con soporte desigual dentro de una misma especificación. Esta es la razón por la que el producto final no es un punto, sino una distribución de muestras que permite calcular intervalos creíbles y predictivos. Y también la razón por la cual naturaleza del producto es <em>ex post</em> y no <em>ex ante</em>: El modelo se ajusta a los datos observados y no a un conocimiento externo.</p>
<p>En términos generales, conforme el <a href="../../apuntes/calculo-incertidumbre-y-optimizacion/introduccion-al-calculo-de-probabilidades/#fórmula-de-bayes">teorema de Bayes</a>, queremos estimar la distribución a posteriori de los parámetros del modelo, dado un conjunto de datos observados. Esto nos permite cuantificar la incertidumbre en nuestras estimaciones y hacer inferencias sobre el comportamiento futuro del sistema que estamos modelando. Sea <span class="math inline">\(P\left( \mathbf{w} |y_{i},\mathbf{x}_{i} \right)\)</span> la distribución a posteriori de los parámetros <span class="math inline">\(\mathbf{w}\in \mathbb{R}^{n}\)</span> dado un conjunto de datos observados <span class="math inline">\((y_{i},\mathbf{x}_{i})\)</span>, para <span class="math inline">\(i=1,\ldots,m\)</span>. Según el teorema de Bayes, esta distribución se puede expresar como</p>
<p><span class="math display">\[
\begin{array}{lll}P\left( \mathbf{w} |y_{i},\mathbf{x}_{i} \right)&amp;=&amp;\dfrac{\overbrace{P\left( y_{i}|\mathbf{x}_{i} ,\mathbf{w} \right)}^{\text{verosimilitud}} \overbrace{P\left( \mathbf{w} \right)}^{\text{a priori}}}{\underbrace{\displaystyle \int P\left( y_{i}|\mathbf{x}_{i} ,\mathbf{w} \right) P\left( \mathbf{w} \right) d\mathbf{w}}_{\text{evidencia}}}\\ &amp;\propto&amp;P\left( y_{i}|\mathbf{x}_{i} ,\mathbf{w} \right) P\left( \mathbf{w} \right)\end{array}
\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(P\left( y_{i}|\mathbf{x}_{i} ,\mathbf{w} \right)\)</span> es la verosimilitud de los datos observados dado los parámetros del modelo.</li>
<li><span class="math inline">\(P\left( \mathbf{w} \right)\)</span> es la distribución a priori de los parámetros del modelo, que refleja nuestro conocimiento previo sobre los mismos antes de observar los datos.</li>
<li><span class="math inline">\(P\left( y_{i}|\mathbf{x}_{i} ,\mathbf{w} \right) P\left( \mathbf{w} \right)\)</span> es la distribución conjunta de los datos y los parámetros del modelo. La multiplicación implica que estas son estadísticamente independientes, lo que es una suposición común en modelos Bayesianos.</li>
<li><span class="math inline">\(\int P\left( y_{i}|\mathbf{x}_{i} ,\mathbf{w} \right) P\left( \mathbf{w} \right) d\mathbf{w}\)</span> es la evidencia, que normaliza la distribución a posteriori y asegura que su cobertura en todo el espacio sea igual a <span class="math inline">\(1\)</span>, conforme los axiomas de probabilidad.</li>
</ul>
<p>La evidencia suele ser muy difícil de calcular, especialmente en modelos complejos con muchos parámetros. Por ello, en la práctica, a menudo se trabaja con la distribución a posteriori sin normalizar, es decir, considerando la proporcionalidad entre la distribución a priori y la distribución conjunta de los datos y los parámetros del modelo. Esto nos permite realizar inferencias sobre los parámetros del modelo sin necesidad de calcular la evidencia explícitamente.</p>
<p>Por cierto, el vector de parámetros <span class="math inline">\(\mathbf{w}\)</span> incluye el sesgo, los coeficientes de las variables contextuales, las escalas jerárquicas y la varianza del ruido.</p>
<p>En la práctica, la construcción del modelo Bayesiano se realiza por medio de la librería <strong><font color="darkmagenta">PyMC</font></strong>, la que permite definir el modelo y aproximar la distribución a posteriori de los parámetros mediante métodos de muestreo avanzados como el uso de métodos de Monte Carlo basados en cadenas de Markov (MCMC, del inglés <em>Markov chain Monte Carlo</em>). Por otro lado, la librería <strong><font color="darkmagenta">ArviZ</font></strong> nos permite almacenar las muestras etiquetadas y realizar diagnósticos sobre la convergencia y la calidad del muestreo conforme las cadenas de Markov generadas.</p>
</section>
<section id="modelo-jerárquico-de-efectos-globales" class="level2">
<h2 class="anchored" data-anchor-id="modelo-jerárquico-de-efectos-globales">Modelo jerárquico de efectos globales</h2>
<p>Para el día <span class="math inline">\(d\)</span>, nuestro modelo de tratamiento tiene la siguiente ecuación estructural:</p>
<p><span class="math display">\[
y_{d}=\mathcal{N} \left( \underbrace{\alpha +\sum_{j=1}^{J_{x}} \tilde{x}_{dj} \beta_{j} +\sum_{r=1}^{J_{z}} \tilde{z}_{dr} \gamma_{r} +\sum_{s=1}^{J_{h}} \tilde{h}_{ds} \delta_{s} +u_{c[d]}}_{=\mu_{d} \rightarrow \text{suma de efectos globales}} ,\underbrace{\sigma_{\text{obs}}^{2}}_{=\text{ruido operacional}} \right)
\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(y_{d}\)</span>: Tratamiento observado en tph para el día <span class="math inline">\(d\)</span>.</li>
<li><span class="math inline">\(\mu_{d}=\alpha +\sum_{j=1}^{J_{x}} \tilde{x}_{dj} \beta_{j} +\sum_{r=1}^{J_{z}} \tilde{z}_{dr} \gamma_{r} +\sum_{s=1}^{J_{h}} \tilde{h}_{ds} \delta_{s} +u_{c[d]}\)</span> es un modelo de regresión lineal que combina efectos globales y jerárquicos, y que constituye el <strong>punto de partida</strong> para la inferencia Bayesiana, ya que permite estimar valores a priori encapsulados en los parámetros de la regresión.</li>
<li><span class="math inline">\(\sigma_{\text{obs}}\)</span>: Desviación estándar asociada a ruido no explicado por el modelo, que asumiremos que representa la variabilidad operacional de la planta concentradora que no depende de aspectos contextuales.</li>
<li><span class="math inline">\(\alpha\)</span>: Parámetro de sesgo que representa el nivel promedio de tratamiento para todas las firmas geológicas.</li>
<li><span class="math inline">\(\tilde{x}_{dj}\)</span>: Variables contextuales estandarizadas que representan el estado de sistemas periféricos de la molienda y la granulometría de alimentación.</li>
<li><span class="math inline">\(\tilde{z}_{dr}\)</span>: Variables contextuales asociadas a las fuentes de mineral, con dependencia espacial, las que omiten una categoría de referencia para evitar colinealidad.</li>
<li><span class="math inline">\(\tilde{h}_{ds}\)</span>: Variables contextuales asociadas a la dureza in-situ del mineral, las que omiten la categoría <code>medium</code> para evitar colinealidad.</li>
<li><span class="math inline">\(u_{c[d]}\)</span>: Efecto jerárquico que representa el desvío de la firma geológica asignada al día <span class="math inline">\(d\)</span>, con suma nula para garantizar la identificabilidad del sesgo <span class="math inline">\(\alpha\)</span>.</li>
</ul>
<p>Escogemos la distribución normal para modelar el tratamiento observado porque es una variable continua agregada, siendo esta distribución una aproximación razonable para este tipo de datos. Sin embargo, esta elección implica asumir que los residuos condicionales con respecto a los tratamientos de molienda observados son simétricos y tienen varianza constante, dependiendo únicamente de la gestión operacional. No se incorporan aspectos más complejos, tales como autocorrelación ni colas robustas; esas limitaciones se declaran de manera previa en el mismo proyecto.</p>
<p>Los coeficientes <span class="math inline">\(\beta_{j},\gamma_{r}\)</span> y <span class="math inline">\(\delta_{s}\)</span> representan los efectos de las variables contextuales estandarizadas, describiendo asimismo los <strong>efectos globales</strong> de cada covariable sobre el tratamiento esperado. Dicho de manera más formal, la misma relación entre una covariable y el tratamiento esperado se aplica a todos los días y firmas geológicas. De esta manera, con variables ya estandarizadas, la derivada parcial de la media esperada con respecto a una covariable es igual al coeficiente respectivo:</p>
<p><span class="math display">\[
\frac{\partial \mu_{d}}{\partial \tilde{x}_{dj}} =\beta_{j} \quad ;\quad \frac{\partial \mu_{d}}{\partial \tilde{z}_{dr}} =\gamma_{r} \quad ;\quad \frac{\partial \mu_{d}}{\partial \tilde{h}_{ds}} =\delta_{s}
\]</span></p>
<p>En este modelo, cuando hablamos de “global”, no nos referimos a causalidad ni universalidad, sino a que no permitimos que la pendiente cambie por cluster, mes o línea. Esta elección de modelamiento controla la complejidad del modelo frente a los 716 días observados del contrato diario completo. Dentro del <em>backtesting</em>, cada ajuste utiliza cerca de 358 días de entrenamiento. Alternativas más sofisticadas podrían permitir pendientes variables por firma, pero añadirían parámetros e interacciones que necesitarían soporte y validación propios.</p>
<p>Procedimentalmente, cada variable contextual se estandariza dentro del conjunto de entrenamiento de cada <em>pliegue de validación</em>, de manera que los coeficientes se expresen aproximadamente en tph por desviación estándar (cambio típico) y los valores a priori de escala sean comparables. El conjunto de prueba utiliza exactamente la misma media y desviación estándar calculadas sobre el conjunto de entrenamiento, ya que se recálculo sobre el conjunto de prueba derivaría en <em>data leakage</em>.</p>
</section>
<section id="identificabilidad-del-parámetro-de-sesgo-y-las-firmas-geológicas" class="level2">
<h2 class="anchored" data-anchor-id="identificabilidad-del-parámetro-de-sesgo-y-las-firmas-geológicas">Identificabilidad del parámetro de sesgo y las firmas geológicas</h2>
<p>Si suponemos que cada firma geológica que caracteriza a la alimentación de la molienda tiene un efecto libre, entonces existe una simetría del tipo</p>
<p><span class="math display">\[
\alpha'=\alpha-a\quad ; \quad u_c'=u_c+a
\]</span></p>
<p>donde <span class="math inline">\(a\)</span> es un valor arbitrario. Esta simetría deja la media esperada de tratamiento <span class="math inline">\(\mu_{d}\)</span> sin cambios, lo que implica que la distribución a posteriori de tratamiento tendría una dirección redundante y el parámetro de sesgo <span class="math inline">\(\alpha\)</span> perdería interpretación. Para evitar esta situación, imponemos una restricción de suma nula sobre los efectos de las firmas geológicas, de manera tal que el parámetro de sesgo <span class="math inline">\(\alpha\)</span> represente el nivel promedio de tratamiento sobre todas las firmas geológicas, y <span class="math inline">\(u_c\)</span> represente un desvío relativo respecto de ese promedio. La restricción se implementa mediante la siguiente parametrización:</p>
<ul>
<li><p>Distribuciones asumidas para los efectos de las firmas geológicas y su escala: <span class="math inline">\(u_{c}^{\text{raw}}\sim \mathcal{N}(0, 1)\)</span> y <span class="math inline">\(\sigma_{u}\sim \bar{\mathcal{N}}(75)\)</span>, donde <span class="math inline">\(\bar{\mathcal{N}}\)</span> representa una distribución normal truncada a valores positivos. El número <span class="math inline">\(75\)</span> representa la escala inicial, en tph, para la desviación estándar de los efectos de las firmas geológicas y permanece declarado como parámetro auditable.</p></li>
<li><p>Transformación de los efectos de las firmas geológicas para garantizar suma nula:</p>
<p><span class="math display">\[
u_{c}=\sigma_{u} \left( u_{c}^{\text{raw}}-\frac{1}{k} \sum_{t=1}^{k} u_{t}^{\text{raw}} \right) \quad ;\quad \sum_{c} u_{c}=0
\]</span></p>
<p>donde <span class="math inline">\(k\)</span> es el número total de firmas geológicas, <span class="math inline">\(u_{c}^{\text{raw}}\)</span> son los efectos de las firmas geológicas sin restricción, y <span class="math inline">\(u_{c}\)</span> son los efectos transformados que cumplen la restricción de suma nula.</p></li>
</ul>
<p>Bajo esta parametrización, la distribución a posteriori de los efectos de las firmas geológicas se centra alrededor de cero, y el parámetro de sesgo <span class="math inline">\(\alpha\)</span> representa el nivel promedio de tratamiento sobre todas las firmas geológicas. Esto permite interpretar los efectos de las firmas geológicas como desviaciones relativas respecto del promedio, lo que facilita la comprensión y comunicación de los resultados del modelo. A nivel de código, la restricción se implementa de la siguiente manera:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>signature_raw <span class="op">=</span> pm.Normal(<span class="st">"signature_raw"</span>, <span class="fl">0.0</span>, <span class="fl">1.0</span>, dims<span class="op">=</span><span class="st">"signature"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>signature_effect <span class="op">=</span> pm.Deterministic(</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"signature_effect"</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    (signature_raw <span class="op">-</span> pt.mean(signature_raw)) <span class="op">*</span> sigma_signature,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    dims<span class="op">=</span><span class="st">"signature"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>donde <code>signature_raw</code> representa los efectos de las firmas geológicas sin restricción, y <code>signature_effect</code> representa los efectos transformados que cumplen la restricción de suma nula. La media de <code>signature_raw</code> se resta de cada efecto individual, y luego se multiplica por la escala <code>sigma_signature</code> para obtener los efectos finales que se utilizan en el modelo. La librería <strong><font color="darkmagenta">PyMC</font></strong> se importa por medio del alias <code>pm</code>.</p>
<p>Estas transformaciones tienen un subtexto más bien práctico: La parametrización permite mantener una única base para el gráfico de cascada que deseamos construir, conforme al diseño de la <a href="#fig-idea" class="quarto-xref">Figura&nbsp;1</a>. No se añade un segundo sesgo geológico, lo que simplifica la interpretación de los resultados y facilita la comunicación de los efectos de las firmas geológicas en el tratamiento esperado.</p>
</section>
<section id="agrupamiento-parcial-para-variables-de-procedencia-y-dureza-insitu" class="level2">
<h2 class="anchored" data-anchor-id="agrupamiento-parcial-para-variables-de-procedencia-y-dureza-insitu">Agrupamiento parcial para variables de procedencia y dureza in–situ</h2>
<p>Las categorías de procedencia y dureza in–situ tienen soportes muy diferentes, porque el modelo de dureza no está definido para todos los bloques que caracterizan al yacimiento minero, y el mismo modelo de bloques no se aplica a todas las fuentes de mineral (por ejemplo, los stocks mina, por su naturaleza transitoria, no disponen de un modelo de bloques). Estimar cada coeficiente con un valor a priori completamente independiente permitiría efectos extremos en categorías sin soporte estadístico significativo. Para evitar esto, usamos escalas compartidas para los efectos de procedencia y dureza in–situ, lo que permite que los datos aprendan la variabilidad sistemática de cada grupo de categorías y regularicen los efectos individuales en consecuencia. Esta técnica se conoce como <strong>agrupamiento parcial</strong>, y permite que los grupos con pocos datos “tomen prestada” información de los demás, evitando estimaciones extremas y mejorando la estabilidad del modelo.</p>
<p>Para la procedencia, asumimos que los efectos de las categorías de procedencia <span class="math inline">\(k\)</span> se distribuyen normalmente alrededor de cero, con una desviación estándar <span class="math inline">\(\sigma_z\)</span> que es aprendida a partir de los datos:</p>
<p><span class="math display">\[
\eta_{k} \sim \mathcal{N} \left( 0,1 \right) \quad ;\quad \sigma_{z} \sim \bar{\mathcal{N}} \left( 55 \right) \quad ;\quad \gamma_{k} =\sigma_{z} \eta_{k}
\]</span></p>
<p>Y para la dureza in–situ, asumimos que los efectos de las categorías de dureza <span class="math inline">\(m\)</span> se distribuyen normalmente alrededor de cero, con una desviación estándar <span class="math inline">\(\sigma_h\)</span> que también es aprendida a partir de los datos:</p>
<p><span class="math display">\[
\xi_{m} \sim \mathcal{N} \left( 0,1 \right) \quad ;\quad \sigma_{h} \sim \bar{\mathcal{N}} \left( 45 \right) \quad ;\quad \delta_{m} =\sigma_{h} \xi_{m}
\]</span></p>
<p>Si la correspondiente familia de categorías muestra poca variabilidad sistemática, la escala se contrae y todos los efectos colapsan a cero. Si existe señal consistente, la escala puede crecer. La expresión <span class="math inline">\(\gamma_{k} =\sigma_{z} \eta_{k}\)</span> es una parametrización no centrada, que en jerarquías débiles suele producir una geometría a posterior más fácil para métodos MCMC como Monte Carlo Hamiltoniano, porque separa la variable estandarizada de su escala. Esta técnica de agrupamiento parcial es más flexible que forzar igualdad entre los efectos de las categorías, y más regularizada que estimar cada categoría sin relación, lo que permite obtener estimaciones más robustas y confiables para las categorías con pocos datos.</p>
</section>
<section id="valores-a-priori-empíricos-para-efectos-regulares" class="level2">
<h2 class="anchored" data-anchor-id="valores-a-priori-empíricos-para-efectos-regulares">Valores a priori empíricos para efectos regulares</h2>
<p>Conforme el modelo de efectos globales, para las variables no composicionales, los <strong>efectos regulares</strong> descritos por los coeficientes <span class="math inline">\(\beta_{j}\)</span> se estiman a partir de un modelo de regresión lineal ajustado a los datos de entrenamiento. Para cada coeficiente <span class="math inline">\(\beta_{j}\)</span>, se asume una distribución normal con media igual al valor estimado por la regresión lineal y desviación estándar igual a dos veces el error estándar robusto estimado por la regresión lineal. Esta elección de valor a priori empírico permite que los efectos regulares se ajusten a los datos observados, mientras que la desviación estándar más amplia permite cierta flexibilidad en la estimación de los efectos regulares, permitiendo una banda creíble más amplia para los efectos regulares y evitando que el modelo se sobreajuste a los datos de entrenamiento. La elección de dos veces el error estándar robusto es una heurística que permite capturar la variabilidad de los efectos regulares sin ser demasiado restrictivo, y se puede ajustar según la naturaleza de los datos y la complejidad del modelo.</p>
<p>La corrección de errores estándar robustos se realiza mediante la estimación de la matriz de covarianza de los errores utilizando el <a href="https://en.wikipedia.org/wiki/Newey%E2%80%93West_estimator"><strong>método de consistencia Newey-West o HAC</strong></a> (del inglés <em>heteroscedasticity and autocorrelation consistent</em>), que permite obtener estimaciones más precisas de los errores estándar en presencia de heterocedasticidad y autocorrelación en los datos. La elección de un retardo o <em>lag</em> igual a <span class="math inline">\(7\)</span> para la corrección HAC es una decisión basada en la naturaleza de los datos y la estructura temporal del modelo, y puede ajustarse según sea necesario:</p>
<p><span class="math display">\[
\hat{\mathrm{Var}}_{\text{HAC}} (\hat{\beta} )=\left( \mathbf{X}^{\top} \mathbf{X} \right)^{-1} \hat{\Omega}_{\text{HAC}} \left( \mathbf{X}^{\top} \mathbf{X} \right)^{-1}
\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(\hat{\mathrm{Var}}_{\text{HAC}} (\hat{\beta} )\)</span> es la matriz de covarianza de los errores estándar robustos estimada mediante el método HAC.</li>
<li><span class="math inline">\(\mathbf{X}\)</span> es la matriz de diseño del modelo de regresión lineal.</li>
<li><span class="math inline">\(\hat{\Omega}_{\text{HAC}}\)</span> es la matriz de covarianza de los errores estimada mediante el método HAC.</li>
</ul>
<p>Luego, para cada coeficiente <span class="math inline">\(\beta_{j}\)</span>, se asume la siguiente distribución a priori:</p>
<p><span class="math display">\[
\beta_{j} \sim \mathcal{N} \left( \hat{\beta}_{j}^{\text{OLS}} ,2\  \mathrm{SE}_{\text{rob}} \left( \hat{\beta}_{j}^{\text{OLS}} \right) \right)
\]</span></p>
<p>donde <span class="math inline">\(\hat{\beta}_{j}^{\text{OLS}}\)</span> es el valor estimado del coeficiente <span class="math inline">\(\beta_{j}\)</span> mediante el modelo de regresión lineal, y <span class="math inline">\(\mathrm{SE}_{\text{rob}} \left( \hat{\beta}_{j}^{\text{OLS}} \right)\)</span> es el error estándar robusto estimado mediante el método HAC. La elección de una desviación estándar igual a <span class="math inline">\(2\)</span>$ veces el error estándar robusto permite capturar la variabilidad de los efectos regulares sin ser demasiado restrictivo, y se puede ajustar según la naturaleza de los datos y la complejidad del modelo.</p>
<p>A fin de no generar estimaciones demasiado optimistas, la construcción de los valores a priori empíricos se realiza dentro de cada <em>pliegue</em> de validación, utilizando únicamente los datos de entrenamiento. De esta manera, se evita que el modelo se sobreajuste a los datos de prueba y se garantiza que las estimaciones sean más robustas y confiables. Para ello, el modelo Bayesiano se convierte en una especie de entidad <em>viva</em> que se ajusta siempre en un año móvil de entrenamiento, generando proyecciones a modo de <em>backtesting</em> sobre los dos meses siguientes. Esta estrategia permite evaluar la capacidad del modelo para generalizar a datos no vistos y proporciona una medida más realista de su desempeño en situaciones del mundo real.</p>
<p>En el esquema Bayesiano, el sesgo <span class="math inline">\(\alpha\)</span> y la desviación estándar del ruido <span class="math inline">\(\sigma_{\text{obs}}\)</span> también se estiman a partir de los datos de entrenamiento, utilizando una distribución normal para el sesgo y una distribución normal truncada a valores positivos para la desviación estándar del ruido. La elección de estas distribuciones permite capturar la variabilidad de los parámetros sin ser demasiado restrictivo, y se puede ajustar según la naturaleza de los datos y la complejidad del modelo:</p>
<p><span class="math display">\[
\alpha \sim \mathcal{N} \left( \bar{y}_{\mathcal{D}} ,\max \left\{ s_{y},\hat{\sigma}_{\text{OLS}} \right\} \right) \quad ;\quad \sigma_{\text{obs}} \sim \bar{\mathcal{N}} \left( \hat{\sigma}_{\text{OLS}} \right)
\]</span></p>
</section>
<section id="diseño-del-modelo-bayesiano-en-pymc" class="level2">
<h2 class="anchored" data-anchor-id="diseño-del-modelo-bayesiano-en-pymc">Diseño del modelo Bayesiano en <font color="darkmagenta">PyMC</font></h2>
<p><strong><font color="darkmagenta">PyMC</font></strong> es una librería de Python que permite construir modelos probabilísticos y realizar inferencia Bayesiana mediante métodos de muestreo avanzados como MCMC. La librería utiliza un enfoque de programación declarativa, lo que significa que el usuario define el modelo en términos de variables aleatorias y sus relaciones, y la librería se encarga de construir el grafo de dependencias y realizar la inferencia. La ventaja de su uso es que la construcción de los modelos sigue una sintaxis intuitiva y cercana a la notación matemática, lo que facilita la comprensión y comunicación de los modelos probabilísticos. Además, <strong><font color="darkmagenta">PyMC</font></strong> permite realizar diagnósticos de convergencia y análisis de sensibilidad, lo que ayuda a evaluar la calidad de las inferencias obtenidas.</p>
<p>La compilación del grafo de dependencias se realiza mediante la librería <strong><font color="darkmagenta">PyTensor</font></strong>, que permite optimizar el cálculo de las distribuciones a posteriori y mejorar la eficiencia del muestreo. La librería utiliza técnicas de diferenciación automática para calcular los gradientes de las distribuciones a posteriori, lo que permite utilizar métodos de muestreo basados en gradientes como Monte Carlo Hamiltoniano (HMC) y No-U-Turn Sampler (NUTS). Esto mejora la eficiencia del muestreo y permite obtener inferencias más precisas y confiables.</p>
<p>En este proyecto, el diseño del modelo es directo:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> pm.Model(coords<span class="op">=</span>coords):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    regular_train <span class="op">=</span> pm.Data(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>        <span class="st">"regular_train"</span>, X_train, dims<span class="op">=</span>(<span class="st">"obs_train"</span>, <span class="st">"regular_feature"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    alpha <span class="op">=</span> pm.Normal(<span class="st">"alpha"</span>, mu<span class="op">=</span>y_train.mean(), sigma<span class="op">=</span>alpha_scale)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    beta_regular <span class="op">=</span> pm.Normal(</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"beta_regular"</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>        mu<span class="op">=</span>regular_prior_mean,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>        sigma<span class="op">=</span>regular_prior_std,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>        dims<span class="op">=</span><span class="st">"regular_feature"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    mu_train <span class="op">=</span> alpha <span class="op">+</span> pm.math.dot(regular_train, beta_regular)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    mu_train <span class="op">+=</span> pm.math.dot(zone_train, beta_zone)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    mu_train <span class="op">+=</span> pm.math.dot(hardness_train, beta_hardness)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    mu_train <span class="op">+=</span> signature_effect[train_signature_index]</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    pm.Normal(</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"observed_tph"</span>,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>        mu<span class="op">=</span>mu_train,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>        sigma<span class="op">=</span>sigma_observation,</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>        observed<span class="op">=</span>y_train,</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>        dims<span class="op">=</span><span class="st">"obs_train"</span>,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    idata <span class="op">=</span> pm.sample(<span class="op">**</span>sampling, return_inferencedata<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>En este fragmento de código, la clase <code>pm.Model</code> define el modelo probabilístico, el cual suele definirse dentro de un <em>context manager</em> que permite encapsular la definición de las variables aleatorias y sus relaciones. La función <code>pm.Data</code> registra los datos de entrenamiento como una variable aleatoria, lo que permite que el modelo pueda ser actualizado con nuevos datos sin necesidad de redefinirlo. Las variables aleatorias <code>alpha</code>, <code>beta_regular</code>, <code>mu_train</code> y <code>observed_tph</code> representan los parámetros del modelo y la distribución a posteriori de los datos observados. La función <code>pm.sample</code> realiza el muestreo de la distribución a posteriori utilizando métodos MCMC, y devuelve un objeto <code>InferenceData</code> que contiene las muestras obtenidas.</p>
<p>Los argumentos <code>coords</code> (en <code>pm.Model</code>) y <code>dims</code> (en <code>pm.Data</code>, <code>pm.Normal</code> y <code>pm.Deterministic</code>) permiten etiquetar las dimensiones de las variables aleatorias, lo que facilita la interpretación de los resultados y la visualización de las distribuciones a posteriori. En este proyecto, se utilizan las siguientes coordenadas y dimensiones:</p>
<ul>
<li><code>regular_feature</code>: características regulares del modelo.</li>
<li><code>zone_feature</code>: zonas geográficas.</li>
<li><code>hardness_feature</code>: dureza del material.</li>
<li><code>signature</code>: firmas de los datos.</li>
<li><code>obs_train</code>: observaciones de entrenamiento.</li>
</ul>
</section>
<section id="técnica-de-muestreo-sin-giros-en-u-nuts" class="level2">
<h2 class="anchored" data-anchor-id="técnica-de-muestreo-sin-giros-en-u-nuts">Técnica de muestreo sin giros en U (NUTS)</h2>
<p>El muestreo de la distribución a posteriori (para los parámetros del modelo) se realiza mediante el algoritmo No-U-Turn Sampler (NUTS, que literalmente significa <em>muestreo sin giros en U</em>), y que es una variante del método de Monte Carlo Hamiltoniano (HMC). NUTS utiliza gradientes de la distribución a posteriori para proponer nuevas muestras, lo que permite explorar el espacio de parámetros de manera más eficiente que los métodos MCMC más tradicionales. Además, NUTS ajusta automáticamente la longitud de las trayectorias de muestreo para evitar “giros en U” (es decir, trayectorias que se <em>doblan</em> sobre sí mismas), lo que mejora la eficiencia del muestreo y reduce la autocorrelación entre las muestras.</p>
<p>En este proyecto, se utiliza la función <code>pm.sample</code> para realizar el muestreo de la distribución a posteriori utilizando NUTS. La función permite especificar varios parámetros de control, como el número de cadenas de Markov, el número de iteraciones de ajuste y el número de muestras guardadas por cadena. Además, se puede especificar el parámetro <code>target_accept</code>, que controla la tasa de aceptación de las propuestas de muestreo y puede ayudar a reducir el riesgo de divergencias en el muestreo. En este proyecto, seteamos <code>target_accept=0.99</code>, lo que indica que se desea una tasa de aceptación alta y conservadora, lo que puede ayudar a reducir el riesgo de divergencias en el muestreo.</p>
<p>Las <strong>divergencias muestrales</strong> son advertencias que indican que el muestreo no pudo explorar adecuadamente una región de alta curvatura en la distribución a posteriori. Esto puede deberse a una mala parametrización del modelo, escalas inadecuadas o problemas geométricos inherentes a la topología de la distribución a posteriori. Las divergencias pueden afectar la calidad de las inferencias obtenidas y deben ser revisadas cuidadosamente. Después de regenerar los datos sintéticos, la corrida final con cuatro cadenas terminó con cero divergencias, un valor de <span class="math inline">\(\hat R_{\max}=1.01\)</span> y un tamaño efectivo mínimo (<em>bulk ESS</em>) de 894 muestras. Estos diagnósticos respaldan la convergencia del ajuste final. Algunos parámetros de determinados pliegues del <em>backtesting</em> emitieron advertencias de tamaño efectivo menor a 100; por ello, las métricas fuera de muestra deben leerse como una evaluación reproducible del conjunto y no como garantía de estabilidad de cada parámetro local.</p>
</section>
<section id="formato-de-salida-del-modelo-media-a-posteriori-versus-predictibilidad" class="level2">
<h2 class="anchored" data-anchor-id="formato-de-salida-del-modelo-media-a-posteriori-versus-predictibilidad">Formato de salida del modelo: Media a posteriori versus predictibilidad</h2>
<p>Una vez construido el modelo Bayesiano, lo que obtenemos como resultado es una distribución a posteriori de los parámetros que constituyen el modelo de regresión lineal que representa la suma de efectos globales jerárquicos para el tratamiento de molienda. Esta distribución a posteriori nos permite calcular la media esperada de tratamiento para un determinado contexto, así como la incertidumbre asociada a esta estimación. Además, podemos generar predicciones para observaciones futuras, incorporando la variabilidad operacional que no está explicada por el modelo.</p>
<p>En la práctica, para cada muestra <span class="math inline">\(s\)</span> de la distribución a posteriori, calculamos la media esperada de tratamiento <span class="math inline">\(\mu_t^{(s)}\)</span> para un determinado contexto, y luego generamos una predicción para una observación futura <span class="math inline">\(\tilde{y}_t^{(s)}\)</span> agregando ruido operacional <span class="math inline">\(\epsilon_t^{(s)}\)</span>. Esto nos permite obtener una distribución predictiva que refleja tanto la incertidumbre en la estimación de la media como la variabilidad operacional que no está explicada por el modelo.</p>
<p>Matemáticamente, la media esperada de tratamiento para una muestra <span class="math inline">\(s\)</span> en un día <span class="math inline">\(t\)</span> (del conjunto de prueba <span class="math inline">\(\mathcal{T}\)</span>) se calcula como:</p>
<p><span class="math display">\[
\mu_t^{(s)}
=\alpha^{(s)}
+\tilde x_t^\top\beta^{(s)}
+\tilde z_t^\top\gamma^{(s)}
+\tilde h_t^\top\delta^{(s)}
+u_{c[t]}^{(s)}
\]</span></p>
<p>La banda creíble <em>alrededor</em> de este valor medio se construye a partir de los percentiles 5% y 95% de la distribución de <span class="math inline">\(\mu_t^{(s)}\)</span> para todas las muestras <span class="math inline">\(s\)</span>, centrada por supuesto en su mediana (o percentil 50%). Esta banda creíble refleja la incertidumbre en la estimación de la media esperada de tratamiento para el contexto dado. Sin embargo, para generar predicciones para observaciones futuras, debemos agregar ruido operacional <span class="math inline">\(\epsilon_t^{(s)}\)</span> a la media esperada de tratamiento, lo que nos permite obtener una distribución predictiva que refleja tanto la incertidumbre en la estimación de la media como la variabilidad operacional que no está explicada por el modelo:</p>
<p><span class="math display">\[
\tilde{y}_{t}^{(s)} =\mu_{t}^{(s)} +\epsilon_{t}^{(s)} \quad ;\quad \epsilon_{t}^{(s)} \sim \mathcal{N} (0,\sigma_{\text{obs}}^{(s)} )
\]</span></p>
<p>El intervalo predictivo resultante debe ser más ancho que la banda creíble de la media, ya que incorpora tanto la incertidumbre en la estimación de la media como la variabilidad operacional. Comparar observaciones diarias contra el intervalo de la media produciría una cobertura artificialmente baja, ya que no se estaría considerando la variabilidad operacional que puede afectar las observaciones futuras.</p>
<p>La construcción de la distribución predictiva se realiza en el nodo denominado <code>fit_final_identifiable_hierarchical_model</code>, cuya salida está constituida por los datasets <code>"final_inference_data"</code> y <code>"posterior_parameter_summary"</code>. El primero contiene las muestras de la distribución a posteriori de los parámetros del modelo, así como las predicciones generadas para observaciones futuras. El segundo contiene un resumen estadístico de los parámetros del modelo, incluyendo la media, la desviación estándar y los percentiles 5% y 95% de la distribución a posteriori. La salida de este nodo permite realizar análisis posteriores, como la evaluación del desempeño del modelo mediante métricas de error y cobertura predictiva, así como la visualización de las contribuciones de cada variable contextual al tratamiento esperado.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Chequeos predictivos para valores a priori y a posteriori
</div>
</div>
<div class="callout-body-container callout-body">
<p>La documentación de <strong><font color="darkmagenta">PyMC</font></strong> presenta los llamados <em>prior</em> y <em>posterior predictive checks</em> como parte del flujo de validación del modelo. Estos chequeos permiten evaluar si el modelo es capaz de reproducir aspectos relevantes de la distribución observada, generando datos simulados a partir de las distribuciones a priori y a posteriori de los parámetros del modelo. Esto nos permite identificar posibles problemas en la especificación del modelo, como la elección de distribuciones a priori inadecuadas o la falta de capacidad del modelo para capturar la variabilidad observada en los datos.</p>
</div>
</div>
</section>
<section id="procedimiento-de-backtesting" class="level2">
<h2 class="anchored" data-anchor-id="procedimiento-de-backtesting">Procedimiento de <em>backtesting</em></h2>
<p>Para validar los resultados del modelo Bayesiano, a nivel estadístico (digamos, métricas de error y cobertura predictiva) y a nivel de negocio (digamos, confiabilidad de la predicción para la operación), se realiza un procedimiento de <em>backtesting</em> que simula lo que habría sabido el modelo en cada momento del tiempo. Este procedimiento permite evaluar la capacidad del modelo para generalizar a datos no vistos y proporciona una medida más realista de su desempeño en situaciones del mundo real.</p>
<p>Supongamos que disponemos de un conjunto de datos completo <span class="math inline">\(\mathcal{M}\)</span> que contiene un total de <span class="math inline">\(M\)</span> meses de observaciones con granularidad diaria. Para cada fecha de corte <span class="math inline">\(t\)</span>, se define un conjunto de entrenamiento <span class="math inline">\(\mathcal{D}_t\)</span> que contiene los 12 meses anteriores, y un conjunto de prueba <span class="math inline">\(\mathcal{T}_t\)</span> que contiene los dos meses siguientes. Si escribimos los límites en meses, la idea es <span class="math inline">\(\mathcal{D}_t = \{y_{d}, \mathbf{x}_{d}\}_{d=t-12}^{t-1}\)</span> y <span class="math inline">\(\mathcal{T}_t = \{y_{d}, \mathbf{x}_{d}\}_{d=t}^{t+1}\)</span>.</p>
<p>En palabras menos rimbombantes, el modelo se entrena con un año móvil de datos y se prueba con los dos meses siguientes, avanzando el corte en pasos de dos meses, a modo de <em>forecasting</em>. Para el año sintético 2035, la configuración base produce seis pliegues consecutivos y no superpuestos. De esta manera, cada día elegible del período fuera de muestra recibe una predicción que puede compararse con su observación sintética.</p>
<p>En cada ventana móvil, se recalculan las referencias y columnas composicionales con soporte, las medias y desviaciones de estandarización, los coeficientes de regresión lineal y los errores estándar robustos para los valores a priori empíricos, la distribución a posteriori de los parámetros del modelo y el ruido operacional, así como las contribuciones de cada variable contextual al tratamiento esperado para las fechas del conjunto de prueba. Esto permite que el modelo se ajuste a los cambios en la distribución de los datos a lo largo del tiempo y capture la variabilidad operacional que puede afectar las observaciones futuras.</p>
<p>¿La razón? La alimentación de la planta concentradora rota en el tiempo, pero no con una variabilidad tan alta como para que un año de historia no represente el régimen vigente. La ventana móvil permite que el modelo se adapte a los cambios en la distribución de los datos a lo largo del tiempo, capturando la variabilidad operacional que puede afectar las observaciones futuras.</p>
<p>Las métricas de desempeño que se reportan para cada ventana móvil de prueba son las siguientes, siendo <span class="math inline">\(\mathcal{T}:{p}\)</span> el número de días evaluados en el conjunto de prueba:</p>
<ul>
<li>Error cuadrático medio en raíz (RMSE): <span class="math inline">\(\text{RMSE} =\left[ \frac{1}{\mathcal{T}_{p}} \sum_{t=1}^{\mathcal{T}_{p}} (\hat{y}_{t} -y_{t})^{2} \right]^{\frac{1}{2}}\)</span>.</li>
<li>Error medio absoluto (MAE): <span class="math inline">\(\text{MAE} =\frac{1}{\mathcal{T}_{p}} \sum_{t=1}^{\mathcal{T}_{p}} |\hat{y}_{t} -y_{t}|\)</span>.</li>
<li>Sesgo de predicción: <span class="math inline">\(\text{B} =\frac{1}{\mathcal{T}_{p}} \sum_{t=1}^{\mathcal{T}_{p}} (\hat{y}_{t} -y_{t})\)</span>.</li>
<li>Cobertura predictiva nominal al 90%: <span class="math inline">\(\text{Cob}_{90} =\frac{1}{\mathcal{T}_{p}} \sum_{t=1}^{\mathcal{T}_{p}} \mathbb{1}\{q_{0.05,t} \leq y_{t} \leq q_{0.95,t}\}\)</span>, donde <span class="math inline">\(q_{0.05,t}\)</span> y <span class="math inline">\(q_{0.95,t}\)</span> son los percentiles 5% y 95% de la distribución predictiva para el día <span class="math inline">\(t\)</span>, respectivamente. Esta métrica permite evaluar la capacidad del modelo para capturar la variabilidad operacional que puede afectar las observaciones futuras, y proporciona una medida de la confiabilidad de las predicciones generadas por el modelo.</li>
</ul>
<p>Después de regenerar el proyecto con datos completamente sintéticos, la corrida reproducible publicada evaluó 358 días fuera de muestra, generando predicciones para cada uno de ellos y comparándolas con las observaciones sintéticas. Los resultados obtenidos fueron los siguientes:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Métrica fuera de muestra</th>
<th style="text-align: right;">Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Días evaluados</td>
<td style="text-align: right;">358</td>
</tr>
<tr class="even">
<td style="text-align: left;">RMSE</td>
<td style="text-align: right;">102.83 tph</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MAE</td>
<td style="text-align: right;">89.71 tph</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sesgo predictivo</td>
<td style="text-align: right;">+0.0234 tph</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cobertura predictiva nominal al 90%</td>
<td style="text-align: right;">92.74%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Divergencias durante el <em>backtesting</em></td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>El sesgo agregado es prácticamente nulo frente al nivel sintético medio de 2231.79 tph: La diferencia media entre predicción y observación es de sólo +0.0234 tph. Esta cancelación no significa que cada <em>pliegue</em> sea insesgado. De hecho, los seis pliegues muestran sesgos aproximados de −21.36, −24.11, −3.65, +11.22, +24.74 y +13.15 tph, respectivamente. El cambio de signo explica por qué el promedio global queda tan cerca de cero y recuerda que una única cifra agregada puede esconder variación temporal.</p>
<p>La cobertura predictiva alcanza 92.74%, algo por encima del 90% nominal. En esta corrida, los intervalos predictivos son levemente conservadores: Contienen la observación en cerca de 93 de cada 100 días evaluados. La proximidad al nivel nominal es una señal favorable de calibración agregada, aunque no reemplaza la inspección por pliegue ni elimina las advertencias de tamaño efectivo observadas en algunos ajustes móviles.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>¿Y por qué no se reporta el R²?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Cualquier usuario de modelos de regresión lineal está acostumbrado a reportar el coeficiente de determinación <span class="math inline">\(R^2\)</span> como una métrica de desempeño. Sin embargo, en este proyecto no se reporta esta métrica por una razón fundamental: No estamos interesados en representar la variabilidad del proceso de molienda por medio de este modelo. Desde un principio, al usar variables contextuales para buscar un nivel esperado de tratamiento, aceptamos que la variabilidad operacional de la planta queda excluida de los factores que gobiernan este modelo, siendo representada por un nivel de ruido que, en términos de reportabilidad, representa toda aquella gestión que <em>responde</em> al contexto que el modelo puede observar. El tratamiento de molienda varía en espacios de tiempo pequeños, de horas hasta a minutos. El modelo consume datos diarios y, por definición, no puede capturar esa variabilidad. Por lo tanto, el <span class="math inline">\(R^2\)</span> no es una métrica relevante para evaluar el desempeño del modelo en este contexto, y se prefiere reportar métricas de error y cobertura predictiva que reflejen la capacidad del modelo para generar predicciones confiables y útiles para describir el nivel esperado de tratamiento de molienda en la planta concentradora, dejando las <em>explicaciones</em> operacionales a la gestión de la planta concentradora, que es la que puede responder a los cambios de niveles en tiempo real.</p>
</div>
</div>
<p>El nodo encargado de realizar el procedimiento de <em>backtesting</em> es <code>run_rolling_twelve_month_backtest</code>, y su salida está constituida por los datasets <code>"backtest_predictions"</code>, <code>"backtest_fold_metrics"</code> y <code>"backtest_summary"</code>. El primero contiene las predicciones generadas para cada día evaluado, incluyendo cobertura predictiva y percentiles de la distribución predictiva. El segundo contiene las métricas de desempeño calculadas para cada ventana móvil de prueba. El tercero contiene un resumen de las métricas de desempeño para todas las ventanas móviles de prueba. La salida de este nodo permite realizar análisis posteriores, como la evaluación del desempeño del modelo mediante métricas de error y cobertura predictiva, así como la visualización de las contribuciones de cada variable contextual al tratamiento esperado.</p>
</section>
<section id="auditabilidad-de-la-inferencia-bayesiana" class="level2">
<h2 class="anchored" data-anchor-id="auditabilidad-de-la-inferencia-bayesiana">Auditabilidad de la inferencia Bayesiana</h2>
<p>A fin de que la inferencia Bayesiana sea auditada, se guardan las contribuciones de cada variable contextual al tratamiento esperado para cada día evaluado en el procedimiento de <em>backtesting</em>. Esto permite que los resultados del modelo puedan ser revisados y verificados por terceros, asegurando la transparencia y confiabilidad de las inferencias obtenidas.</p>
<p>Para cada variable no composicional, se guarda la contribución de cada coeficiente <span class="math inline">\(\beta_{j}^{(s)}\)</span> a la media esperada de tratamiento <span class="math inline">\(\mu_t^{(s)}\)</span> para cada muestra <span class="math inline">\(s\)</span> de la distribución a posteriori:</p>
<p><span class="math display">\[
C_{tj}^{(s)}=\tilde{x}_{tj} \beta_{j}^{(s)} \quad ;\quad \widehat{C}_{tj} =\frac{1}{S} \sum_{s} C_{tj}^{(s)}
\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(C_{tj}^{(s)}\)</span> es la contribución de la variable contextual <span class="math inline">\(j\)</span> al tratamiento esperado para el día <span class="math inline">\(t\)</span> en la muestra <span class="math inline">\(s\)</span> de la distribución a posteriori.</li>
<li><span class="math inline">\(\tilde{x}_{tj}\)</span> es el valor estandarizado de la variable contextual <span class="math inline">\(j\)</span> para el día <span class="math inline">\(t\)</span>.</li>
<li><span class="math inline">\(\beta_{j}^{(s)}\)</span> es el coeficiente correspondiente a la variable contextual <span class="math inline">\(j\)</span> en la muestra <span class="math inline">\(s\)</span> de la distribución a posteriori.</li>
<li><span class="math inline">\(\widehat{C}_{tj}\)</span> es la contribución promedio de la variable contextual <span class="math inline">\(j\)</span> al tratamiento esperado para el día <span class="math inline">\(t\)</span>, calculada como el promedio de las contribuciones <span class="math inline">\(C_{tj}^{(s)}\)</span> sobre todas las muestras <span class="math inline">\(s\)</span> de la distribución a posteriori.</li>
</ul>
<p>Las variables contextuales geoespaciales, como procedencia y dureza in–situ, utilizan productos matriciales para calcular sus contribuciones a la media esperada de tratamiento, y la firma geológica indexa el efecto correspondiente. La media posterior de la media esperada de tratamiento para cada día <span class="math inline">\(t\)</span> se calcula finalmente como:</p>
<p><span class="math display">\[
\widehat{\mu}_t = \widehat{\alpha} + \widehat{C}_{t,\text{geología}} + \widehat{C}_{t,\text{procedencia}} + \widehat{C}_{t,\text{dureza}} + \sum_j \widehat{C}_{tj}
\]</span></p>
<p>Esta indentidad permite que el modelo sea interpretado como un <strong>producto explicativo</strong> (¡pero no causal!), donde cada variable contextual contribuye de manera transparente al tratamiento esperado. Además, la reportería puede agregar las contribuciones por período sin necesidad de volver a abrir ni resumir manualmente la distribución a posteriori, lo que facilita la auditoría y verificación de los resultados del modelo.</p>
<p><a href="../../proyectos/bayesian-tph-forecasting/04-ciencia-de-datos.html">← Ciencia de datos</a> · <a href="../../proyectos/bayesian-tph-forecasting/06-bridge-app-y-operacion.html">Siguiente: Producto final, app y operación →</a></p>


</section>

</main> <!-- /main -->
<div id="notes-prev-next" class="page-nav-links"></div>

<script>
document.addEventListener("DOMContentLoaded", function () {
  // ==========================================================================
  // El arreglo `notesOrder` se GENERA automáticamente a partir del parámetro
  // `number-offset` del front matter de cada entrada, mediante el script
  // scripts/build-notes-order.py (hook pre-render de Quarto). Así el orden
  // anterior/siguiente siempre refleja la numeración real de cada sección.
  // No editar el bloque entre los marcadores a mano: se sobrescribe en el build.
  // ==========================================================================
  /* NOTES_ORDER_START */
  const notesOrder = [
    {
        "section": "apuntes/calculo-incertidumbre-y-optimizacion",
        "items": [
            {
                "title": "Cálculo diferencial",
                "href": "/apuntes/calculo-incertidumbre-y-optimizacion/calculo-diferencial/"
            },
            {
                "title": "Aplicaciones del cálculo diferencial",
                "href": "/apuntes/calculo-incertidumbre-y-optimizacion/aplicaciones-del-calculo-diferencial/"
            },
            {
                "title": "Probabilidad elemental",
                "href": "/apuntes/calculo-incertidumbre-y-optimizacion/probabilidad-clasica/"
            },
            {
                "title": "Introducción al cálculo de probabilidades",
                "href": "/apuntes/calculo-incertidumbre-y-optimizacion/introduccion-al-calculo-de-probabilidades/"
            },
            {
                "title": "Distribuciones específicas de probabilidad",
                "href": "/apuntes/calculo-incertidumbre-y-optimizacion/distribuciones-especificas-de-probabilidad/"
            },
            {
                "title": "Introducción a la teoría de optimización",
                "href": "/apuntes/calculo-incertidumbre-y-optimizacion/introduccion-a-la-teoria-de-optimizacion/"
            },
            {
                "title": "Optimización de tipo black-box",
                "href": "/apuntes/calculo-incertidumbre-y-optimizacion/optimizacion-de-tipo-black-box/"
            },
            {
                "title": "Optimización aplicada a machine learning",
                "href": "/apuntes/calculo-incertidumbre-y-optimizacion/optimizacion-aplicada-al-aprendizaje-automatico/"
            }
        ]
    },
    {
        "section": "apuntes/estructuras-lineales",
        "items": [
            {
                "title": "Espacios vectoriales",
                "href": "/apuntes/estructuras-lineales/espacios-vectoriales/"
            },
            {
                "title": "Bases y dimensión",
                "href": "/apuntes/estructuras-lineales/bases-y-dimension/"
            },
            {
                "title": "Transformaciones lineales",
                "href": "/apuntes/estructuras-lineales/transformaciones-lineales/"
            },
            {
                "title": "Producto interno",
                "href": "/apuntes/estructuras-lineales/producto-interno/"
            },
            {
                "title": "Determinantes y diagonalización",
                "href": "/apuntes/estructuras-lineales/determinantes-y-diagonalizacion/"
            },
            {
                "title": "Una introducción a las formas",
                "href": "/apuntes/estructuras-lineales/introduccion-a-las-formas/"
            },
            {
                "title": "Descomposiciones matriciales",
                "href": "/apuntes/estructuras-lineales/descomposiciones-matriciales/"
            }
        ]
    },
    {
        "section": "apuntes/grafos-e-informacion",
        "items": [
            {
                "title": "Una (no tan breve) introducción a la teoría de grafos",
                "href": "/apuntes/grafos-e-informacion/teoria-de-grafos/"
            },
            {
                "title": "Optimización de redes computacionales",
                "href": "/apuntes/grafos-e-informacion/optimizacion-de-grafos/"
            },
            {
                "title": "Introducción a la teoría de la información",
                "href": "/apuntes/grafos-e-informacion/introduccion-a-la-teoria-de-la-informacion/"
            },
            {
                "title": "Cadenas de Markov",
                "href": "/apuntes/grafos-e-informacion/cadenas-de-markov/"
            }
        ]
    },
    {
        "section": "apuntes/tensores-y-variedades",
        "items": [
            {
                "title": "Una primera aproximación a los tensores",
                "href": "/apuntes/tensores-y-variedades/introducion-a-los-tensores/"
            },
            {
                "title": "Introducción al álgebra tensorial",
                "href": "/apuntes/tensores-y-variedades/introducion-al-algebra-tensorial/"
            },
            {
                "title": "Un cuento que versa sobre topología",
                "href": "/apuntes/tensores-y-variedades/introduccion-a-la-topologia/"
            },
            {
                "title": "Variedades y fibrados vectoriales",
                "href": "/apuntes/tensores-y-variedades/introduccion-a-las-variedades/"
            }
        ]
    },
    {
        "section": "clases/data-analytics/introduccion-al-analisis-de-datos-en-python/computacion-vectorizada-y-arreglos-con-numpy",
        "items": [
            {
                "title": "Introducción a Numpy",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/computacion-vectorizada-y-arreglos-con-numpy/introduccion-a-numpy/"
            },
            {
                "title": "Operatoria en Numpy",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/computacion-vectorizada-y-arreglos-con-numpy/operatoria-en-numpy/"
            },
            {
                "title": "Operaciones de agregación",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/computacion-vectorizada-y-arreglos-con-numpy/broadcasting-y-agregacion/"
            },
            {
                "title": "Comparación, ordenamiento y reemplazos en arreglos",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/computacion-vectorizada-y-arreglos-con-numpy/comparacion-ordenamiento-y-reemplazo/"
            },
            {
                "title": "Aplicación de Numpy en la construcción de modelos predictivos",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/computacion-vectorizada-y-arreglos-con-numpy/aplicaciones-en-modelos/"
            }
        ]
    },
    {
        "section": "clases/data-analytics/introduccion-al-analisis-de-datos-en-python/manipulacion-tabular-y-analisis-con-pandas",
        "items": [
            {
                "title": "Una introducción rápida a Pandas",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/manipulacion-tabular-y-analisis-con-pandas/introduccion-rapida-a-pandas/"
            },
            {
                "title": "Tipos de datos en Pandas",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/manipulacion-tabular-y-analisis-con-pandas/tipos-de-datos-en-pandas/"
            },
            {
                "title": "Manipulación de Series - Parte I",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/manipulacion-tabular-y-analisis-con-pandas/manipulacion-de-series-parte-i/"
            },
            {
                "title": "Manipulación de Series - Parte II",
                "href": "/clases/data-analytics/introduccion-al-analisis-de-datos-en-python/manipulacion-tabular-y-analisis-con-pandas/manipulacion-de-series-parte-ii/"
            }
        ]
    },
    {
        "section": "clases/machine-learning/aprendizaje-supervisado/modelos-lineales",
        "items": [
            {
                "title": "Una introducción sencilla a los algoritmos de aprendizaje",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-lineales/introduccion-algoritmos-aprendizaje/"
            },
            {
                "title": "Una introducción a Scikit-Learn",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-lineales/introduccion-a-scikit-learn/"
            },
            {
                "title": "Modelos de clasificación - Parte I",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-lineales/modelos-de-clasificacion-parte-i/"
            },
            {
                "title": "Modelos de clasificación - Parte II",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-lineales/modelos-de-clasificacion-parte-ii/"
            },
            {
                "title": "Modelo de regresión lineal",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-lineales/modelo-de-regresion-lineal/"
            },
            {
                "title": "Modelos lineales regularizados, Bayesianos y generalizados",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-lineales/modelos-lineales-regularizados-bayesianos-y-generalizados/"
            },
            {
                "title": "Máquinas de soporte vectorial",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-lineales/maquinas-de-soporte-vectorial/"
            }
        ]
    },
    {
        "section": "clases/machine-learning/aprendizaje-supervisado/modelos-no-lineales",
        "items": [
            {
                "title": "Árboles de decisión",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-no-lineales/arboles-de-decision/"
            },
            {
                "title": "Modelos de ensamble",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-no-lineales/modelos-de-ensamble/"
            },
            {
                "title": "Boosting especializado",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-no-lineales/modelos-de-ensamble-especializados/"
            },
            {
                "title": "Estimación de importancia de variables en modelos predictivos",
                "href": "/clases/machine-learning/aprendizaje-supervisado/modelos-no-lineales/importancia-de-variables/"
            }
        ]
    },
    {
        "section": "clases/machine-learning/seleccion-de-variables-metricas-y-tuning",
        "items": [
            {
                "title": "Selección y evaluación de modelos",
                "href": "/clases/machine-learning/seleccion-de-variables-metricas-y-tuning/seleccion-y-evaluacion-de-modelos/"
            }
        ]
    }
];
  /* NOTES_ORDER_END */

  function normalizePath(path) {
    if (!path.endsWith("/")) path += "/";
    path = path.replace(/index\.html\/?$/, "");
    return path;
  }

  const currentPath = normalizePath(window.location.pathname);
  const container = document.getElementById("notes-prev-next");

  let previous = null;
  let next = null;
  let found = false;

  for (const section of notesOrder) {
    const items = section.items;
    const index = items.findIndex(item => normalizePath(item.href) === currentPath);

    if (index !== -1) {
      found = true;
      if (index > 0) previous = items[index - 1];
      if (index < items.length - 1) next = items[index + 1];
      break;
    }
  }

  if (!found) {
    container.style.display = "none";
    return;
  }

  container.innerHTML = `
    <div class="page-nav-prev">
      ${previous ? `<a href="${previous.href}">← ${previous.title}</a>` : ``}
    </div>
    <div class="page-nav-next">
      ${next ? `<a href="${next.href}">${next.title} →</a>` : ``}
    </div>
  `;
});
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© René Quezada</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Hecho con Quarto</p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>