<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Descomposiciones matriciales – Cuaderno técnico</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-868ae146fa83ccfa6cf12e345c634de9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">Cuaderno técnico</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../articulos/index.html"> 
<span class="menu-text">Artículos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../apuntes/index.html"> 
<span class="menu-text">Apuntes</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../clases/index.html"> 
<span class="menu-text">Clases</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../proyectos/index.html"> 
<span class="menu-text">Proyectos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../sobre-mi.html"> 
<span class="menu-text">Sobre mí</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#descomposición-de-cholesky." id="toc-descomposición-de-cholesky." class="nav-link active" data-scroll-target="#descomposición-de-cholesky.">Descomposición de Cholesky.</a></li>
  <li><a href="#descomposición-qr." id="toc-descomposición-qr." class="nav-link" data-scroll-target="#descomposición-qr.">Descomposición QR.</a></li>
  <li><a href="#descomposición-en-valores-singulares." id="toc-descomposición-en-valores-singulares." class="nav-link" data-scroll-target="#descomposición-en-valores-singulares.">Descomposición en valores singulares.</a>
  <ul class="collapse">
  <li><a href="#una-primera-explicación-geométrica." id="toc-una-primera-explicación-geométrica." class="nav-link" data-scroll-target="#una-primera-explicación-geométrica.">Una primera explicación geométrica.</a></li>
  <li><a href="#construcción-de-la-descomposición-en-valores-singulares." id="toc-construcción-de-la-descomposición-en-valores-singulares." class="nav-link" data-scroll-target="#construcción-de-la-descomposición-en-valores-singulares.">Construcción de la descomposición en valores singulares.</a></li>
  </ul></li>
  <li><a href="#aproximación-matricial." id="toc-aproximación-matricial." class="nav-link" data-scroll-target="#aproximación-matricial.">Aproximación matricial.</a></li>
  <li><a href="#comentarios-finales." id="toc-comentarios-finales." class="nav-link" data-scroll-target="#comentarios-finales.">Comentarios finales.</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Descomposiciones matriciales</h1>
<p class="subtitle lead">Factorización, estructura y compresión de información</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Idea central
</div>
</div>
<div class="callout-body-container callout-body">
<p>Las descomposiciones matriciales permiten expresar matrices como productos de matrices con estructura más simple. Esto facilita el análisis de transformaciones lineales, mejora la estabilidad numérica de muchos cálculos y abre la puerta a aplicaciones fundamentales en aproximación, compresión de información y aprendizaje automático.</p>
</div>
</div>
<section id="descomposición-de-cholesky." class="level2">
<h2 class="anchored" data-anchor-id="descomposición-de-cholesky.">Descomposición de Cholesky.</h2>
<p>Como ya hemos revisado en los apuntes anteriores, existen varias formas de descomponer una matriz. Puntualmente, la diagonalización y la descomposición por formas nos han permitido reformular matrices que cumplen con ciertas condiciones en términos de productos de tres matrices.</p>
<p>A continuación vamos a estudiar una nueva descomposición conocida como <strong>factorización de Cholesky</strong>, la que nos permite descomponer una matriz <span class="math inline">\(\mathbf{A}\)</span> que cumple igualmente algunas condiciones en el producto <span class="math inline">\(\mathbf{A}=\mathbf{L}\mathbf{L}^{\top}\)</span>, donde <span class="math inline">\(\mathbf{L}\)</span> es una matriz triangular inferior cuya diagonal contiene números positivos. Sin embargo, para ello, es necesario que las matrices que queremos descomponer sean <strong>definidas positivas</strong>. Este concepto lo revisamos previamente, pero lo refinaremos a fin de considerar matrices definidas sobre cualquier cuerpo (<span class="math inline">\(\mathbb{R}\)</span> o <span class="math inline">\(\mathbb{C}\)</span>).</p>
<p><strong><font color="blue">Definición 7.1 – Matriz definida positiva (otra vez…):</font></strong> Sea <span class="math inline">\(\mathbf{A}\in \mathbb{K}^{n\times n}\)</span> una matriz hermítica. Diremos que <span class="math inline">\(\mathbf{A}\)</span> es una <strong>matriz definida positiva</strong> si cumple con una (y, por tanto, con todas) de las siguientes formulaciones equivalentes:</p>
<ul>
<li><strong>(F1):</strong> Para todos los vectores no nulos <span class="math inline">\(\mathbf{u}\in \mathbb{K}^{n}\)</span>, se tiene que <span class="math inline">\(\mathbf{u}^{\ast}\mathbf{A}\mathbf{u}\)</span>, donde <span class="math inline">\(\mathbf{u}^{\ast}\)</span> es la matriz transpuesta conjugada de <span class="math inline">\(\mathbf{u}\)</span>.</li>
<li><strong>(F2):</strong> Todos los autovalores de <span class="math inline">\(\mathbf{A}\)</span> son positivos.</li>
<li><strong>(F3):</strong> La función <span class="math inline">\(\left&lt; \mathbf{u} ,\mathbf{v} \right&gt;  =\mathbf{v}^{\ast } \mathbf{A} \mathbf{u}\)</span> define un producto interno en <span class="math inline">\(\mathbb{K}^{n}\)</span>.</li>
</ul>
<p>Observamos, de las condiciones anteriores, que si <span class="math inline">\(\mathbf{A}\)</span> es definida positiva, entonces <span class="math inline">\(\det(\mathbf{A})&gt;0\)</span> y su inversa <span class="math inline">\(\mathbf{A}^{-1}\)</span> es también definida positiva.</p>
<p>Estamos pues en condiciones de formular el siguiente teorema.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Teorema 7.1 – Descomposición de Cholesky
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Sea <span class="math inline">\(\mathbf{A}\in \mathbb{K}^{n\times n}\)</span> una matriz simétrica y definida positiva. Entonces <span class="math inline">\(\mathbf{A}\)</span> puede ser expresada como <span class="math inline">\(\mathbf{A}=\mathbf{L}\mathbf{L}^{\top}\)</span>, donde <span class="math inline">\(\mathbf{L}\)</span> es una matriz triangular inferior con elementos positivos en su diagonal principal. Es decir,</em></p>
<p><span class="math display">\[
\mathbf{A} =\left( \begin{matrix}a_{11}&amp;a_{12}&amp;\cdots &amp;a_{1n}\\ a_{21}&amp;a_{22}&amp;\cdots &amp;a_{2n}\\ \vdots &amp;\vdots &amp;\ddots &amp;\vdots \\ a_{n1}&amp;a_{n2}&amp;\cdots &amp;a_{nn}\end{matrix} \right)  =\left( \begin{matrix}l_{11}&amp;0&amp;\cdots &amp;0\\ l_{21}&amp;l_{22}&amp;\cdots &amp;0\\ \vdots &amp;\vdots &amp;\ddots &amp;\vdots \\ l_{n1}&amp;l_{n2}&amp;\cdots &amp;l_{nn}\end{matrix} \right)  \left( \begin{matrix}l_{11}&amp;l_{21}&amp;\cdots &amp;l_{n1}\\ 0&amp;l_{22}&amp;\cdots &amp;l_{n2}\\ \vdots &amp;\vdots &amp;\ddots &amp;\vdots \\ 0&amp;0&amp;\cdots &amp;l_{nn}\end{matrix} \right)  =\mathbf{L} \mathbf{L}^{\top } \tag{7.1}
\]</span></p>
<p><em>La matriz <span class="math inline">\(\mathbf{L}\)</span> se denomina <strong>factor de Cholesky</strong> de <span class="math inline">\(\mathbf{A}\)</span>, y es único.</em></p>
</div>
</div>
<p><strong>Ejemplo 7.1:</strong> Consideremos una matriz simétrica y definida positiva <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{3\times 3}\)</span>, definida como <span class="math inline">\(\mathbf{A} =\left\{ a_{ij}\right\}\)</span>, tal que</p>
<p><span class="math display">\[
\mathbf{A} =\left( \begin{matrix}a_{11}&amp;a_{12}&amp;a_{13}\\ a_{21}&amp;a_{22}&amp;a_{23}\\ a_{31}&amp;a_{32}&amp;a_{33}\end{matrix} \right) \tag{7.2}
\]</span></p>
<p>Vamos a buscar una fórmula para determinar explícitamente los elementos del factor de Cholesky <span class="math inline">\(\mathbf{L}\)</span> de <span class="math inline">\(\mathbf{A}\)</span>. En efecto, <span class="math inline">\(\mathbf{A}=\mathbf{L}\mathbf{L}^{\top}\)</span>, donde</p>
<div class="eq-scroll">
<p><span class="math display">\[
\mathbf{L} \mathbf{L}^{\top } =\left( \begin{matrix}l_{11}&amp;0&amp;0\\ l_{21}&amp;l_{22}&amp;0\\ l_{31}&amp;l_{32}&amp;l_{33}\end{matrix} \right)  \left( \begin{matrix}l_{11}&amp;l_{21}&amp;l_{32}\\ 0&amp;l_{22}&amp;l_{32}\\ 0&amp;0&amp;l_{33}\end{matrix} \right)  =\left( \begin{matrix}l^{2}_{11}&amp;l_{21}l_{11}&amp;l_{31}l_{11}\\ l_{21}l_{31}&amp;l^{2}_{21}+l^{2}_{22}&amp;l_{31}l_{21}+l_{32}l_{22}\\ l_{31}l_{11}&amp;l_{31}l_{21}+l_{32}l_{22}&amp;l^{2}_{31}+l^{2}_{32}+l^{2}_{33}\end{matrix} \right) \tag{7.3}
\]</span></p>
</div>
<p>Comparando el lado derecho de la ecuación (7.2) con el lado derecho de la ecuación (3.175), podemos observar que existe un sencillo patrón en los elementos de la diagonal principal de <span class="math inline">\(\mathbf{L}\)</span>. En efecto,</p>
<p><span class="math display">\[
l_{11}=\sqrt{a_{11}} \  ;\  l_{22}=\sqrt{a_{22}-l^{2}_{21}} \  ;\  l_{33}=\sqrt{a_{33}-\left( l^{2}_{31}+l^{2}_{32}\right)  } \tag{7.4}
\]</span></p>
<p>Similarmente, para los elementos ubicados debajo de la diagonal principal de <span class="math inline">\(\mathbf{L}\)</span> (<span class="math inline">\(l_{ij}\)</span>, donde <span class="math inline">\(i&gt;j\)</span>), también se observa un patrón,</p>
<p><span class="math display">\[
l_{21}=\frac{1}{l_{11}} a_{21}\  ;\  l_{31}=\frac{1}{l_{11}} a_{31}\  ;\  l_{32}=\frac{1}{l_{22}} \left( a_{32}-l_{31}l_{21}\right) \tag{7.5}
\]</span></p>
<p>De esta manera, en términos más generales, para una matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{n\times n}\)</span>, podemos probar (por inducción) que:</p>
<ul>
<li>Para los elementos de la diagonal principal: <span class="math inline">\(l_{ii}=a_{ii}-\sum^{i-1}_{k=1} l^{2}_{ik}\)</span>.</li>
<li>Para el resto de los elementos: <span class="math inline">\(l_{ij}=\frac{1}{l_{jj}} \left( a_{ij}-\sum^{j-1}_{k=1} l_{ik}l_{jk}\right)  ;\forall i&gt;j\)</span>.</li>
</ul>
<p>◼︎</p>
<p><strong>Ejemplo 7.2:</strong> En <strong><font color="darkmagenta">Numpy</font></strong> es posible obtener una descomposición de Cholesky fácilmente por medio de la función <code>cholesky()</code>, cuya dependencia es igualmente el módulo <code>numpy.linalg</code>. Esta función simplemente requiere, como argumento, un arreglo bidimensional que represente a una matriz definida positiva. Por ejemplo:</p>
<div id="176d396f" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="81ab4a83" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos nuestra matriz A.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.array([</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">1</span>],</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">0</span>],</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">2</span>],</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostramos en pantalla esta matriz.</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>A</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>array([[2, 2, 1],
       [2, 3, 0],
       [1, 0, 2]])</code></pre>
</div>
</div>
<div id="2f723eb1" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos su factorización de Cholesky.</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>L <span class="op">=</span> np.linalg.cholesky(A)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostramos la matriz L en pantalla.</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>L</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="3">
<pre><code>array([[ 1.41421356,  0.        ,  0.        ],
       [ 1.41421356,  1.        ,  0.        ],
       [ 0.70710678, -1.        ,  0.70710678]])</code></pre>
</div>
</div>
<p>Es posible verificar que la descompisición obtenida efectivamente genera la matriz original <code>A</code>, realizando la operación <span class="math inline">\(\mathbf{L}\mathbf{L}^{\top}\)</span>. En efecto,</p>
<div id="de11963c" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificamos que la descomposición efectivamente genera la matriz A.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>np.allclose(A, L <span class="op">@</span> L.T)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="4">
<pre><code>True</code></pre>
</div>
</div>
<p>Por supuesto, la factorización de Cholesky exige que las matrices a descomponer sean definidas positivas. En <strong><font color="darkmagenta">Numpy</font></strong> esta no es una excepción, y se levantará un error de tipo <code>LinAlgError</code> si esta condición no se cumple al intentar implementar una decomposición de Cholesky:</p>
<div id="7ad021c8" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos una matriz arbitraria.</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> rng.integers(low<span class="op">=-</span><span class="dv">6</span>, high<span class="op">=</span><span class="dv">6</span>, size<span class="op">=</span>(<span class="dv">4</span>, <span class="dv">4</span>))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>B</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>array([[-5,  3,  1, -1],
       [-1,  4, -5,  2],
       [-4, -5,  0,  5],
       [ 2,  3,  2,  3]])</code></pre>
</div>
</div>
<div id="b89668a2" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Si intentamos calcular su descomposición de Cholesky, se levantará un error, ya que no es</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># definida positiva.</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    L <span class="op">=</span> np.linalg.cholesky(B)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> np.linalg.LinAlgError <span class="im">as</span> e:</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(e)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Matrix is not positive definite</code></pre>
</div>
</div>
<p>◼︎</p>
<p>La descomposición de Cholesky es una herramienta importante en el cálculo numérico subyacente a los algoritmos de aprendizaje. Las matrices simétricas y definidas positivas, con frecuencia, requieren de intensivas manipulaciones para llegar a valores de interés en muchos problemas estadísticos. Por ejemplo, la <em>matriz de covarianza</em> asociada a un <em>vector de variables aleatorias distribuidas normalmente</em> cumple con estas condiciones. La descomposición de Cholesky de esta matriz de covarianza nos permite generar muestreos desde una distribución <em>Gaussiana</em>. También nos permite construir transformaciones lineales de variables aleatorias, lo que se explota enormemente al calcular gradientes en modelos estocásticos de gran profundidad, tales como los <em>auto-enconders</em> de tipo variacionales (Jimenez Rezende et al., 2014; Kingma &amp; Weilling., 2014).</p>
<p>La descomposición de Cholesky también nos permite calcular determinantes de manera eficiente. Dada la factorización <span class="math inline">\(\mathbf{A}=\mathbf{L}\mathbf{L}^{\top}\)</span>, sabemos que <span class="math inline">\(\det(\mathbf{A})=\det(\mathbf{L}) \det(\mathbf{L}^{\top})=\det(\mathbf{L})^{2}\)</span>. Ya que <span class="math inline">\(\mathbf{L}\)</span> es una matriz triangular, el determinante de <span class="math inline">\(\mathbf{L}\)</span> es simplemente el producto de los elementos de la diagonal principal. Por esta razón, muchos paquetes computacionales (y, en varios casos, librerías de Python) utilizan la descomposición de Cholesky para facilitar cálculos que involucran matrices (siempre que sean definidas positivas).</p>
</section>
<section id="descomposición-qr." class="level2">
<h2 class="anchored" data-anchor-id="descomposición-qr.">Descomposición QR.</h2>
<p>Otro tipo de descomposición muy común en álgebra lineal y, puntualmente, en machine learning (sobretodo por el aumento en la eficiencia de ciertos cálculos matriciales), corresponde a la <strong>descomposición QR</strong>. Tal descomposición es válida para cualquier matriz <span class="math inline">\(\mathbf{A}\in \mathbb{K}^{n\times n}\)</span>, y es tal que <span class="math inline">\(\mathbf{A}=\mathbf{Q}\mathbf{R}\)</span>, donde <span class="math inline">\(\mathbf{Q}\)</span> es una matriz ortogonal o unitaria (recordemos que toda matriz <span class="math inline">\(\mathbf{Q}\in \mathbb{K}^{n\times n}\)</span> que satisface la expresión <span class="math inline">\(\mathbf{Q}^{\top}\mathbf{Q}=\mathbf{I}_{n}\)</span> se denomina ortogonal o unitaria) y <span class="math inline">\(\mathbf{R}\)</span> es una matriz triangular superior. Si <span class="math inline">\(\mathbf{A}\)</span> es, además, no singular (y, por tanto, invertible), entonces la descomposición QR es única siempre que los elementos de la diagonal principal de <span class="math inline">\(\mathbf{R}\)</span> sean todos positivos.</p>
<p>La construcción de la factorización QR puede hacerse de varias formas, siendo la más usual el uso de proyecciones ortogonales y del proceso de ortogonalización de Gram-Schmidt. Para ello, consideremos este último proceso aplicado a las columnas de una matriz no singular, digamos <span class="math inline">\(\mathbf{A}=(\mathbf{a}_{1},...,\mathbf{a}_{n})\)</span>, donde <span class="math inline">\(\mathbf{a}_{j} =\left\{ a_{ij}\right\}\)</span> para <span class="math inline">\(i=1,...,n\)</span>, y definimos el producto interno usual <span class="math inline">\(\left&lt; \mathbf{v} ,\mathbf{w} \right&gt;  =\mathbf{v}^{\ast } \mathbf{w}\)</span>. Definimos además la proyección ortogonal</p>
<p><span class="math display">\[
\pi_{\mathbf{u} } \left( \mathbf{a} \right)  =\frac{\left&lt; \mathbf{u} ,\mathbf{a} \right&gt;  }{\left&lt; \mathbf{u} ,\mathbf{u} \right&gt;  } \mathbf{u} =\frac{\left&lt; \mathbf{u} ,\mathbf{a} \right&gt;  }{\left\Vert \mathbf{u} \right\Vert^{2}  } \mathbf{u} \tag{7.6}
\]</span></p>
<p>Entonces, usando el método de Gram-Schmidt, obtenemos</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u}_{1} &amp;=&amp;\mathbf{a}_{1} \  ;\  \mathbf{e}_{1} =\frac{\mathbf{u}_{1} }{\left\Vert \mathbf{u}_{1} \right\Vert^{2}  } \\ \mathbf{u}_{2} &amp;=&amp;\mathbf{a}_{2} -\pi_{\mathbf{u}_{1} } \left( \mathbf{a}_{2} \right)  \  ;\  \mathbf{e}_{2} =\frac{\mathbf{u}_{2} }{\left\Vert \mathbf{u}_{2} \right\Vert^{2}  } \\ \mathbf{u}_{3} &amp;=&amp;\mathbf{a}_{3} -\pi_{\mathbf{u}_{1} } \left( \mathbf{a}_{3} \right)  -\pi_{\mathbf{u}_{2} } \left( \mathbf{a}_{3} \right)  \  ;\  \mathbf{e}_{3} =\frac{\mathbf{u}_{3} }{\left\Vert \mathbf{u}_{3} \right\Vert^{2}  } \\ \vdots &amp;\vdots &amp;\vdots \\ \mathbf{u}_{k} &amp;=&amp;\mathbf{a}_{k} -\sum^{k-1}_{j=1} \pi_{\mathbf{u}_{j} } \left( \mathbf{a}_{k} \right)  \  ;\  \mathbf{e}_{k} =\frac{\mathbf{u}_{k} }{\left\Vert \mathbf{u}_{k} \right\Vert^{2}  } \end{array} \tag{7.7}
\]</span></p>
<p>Podemos expresar las columnas <span class="math inline">\(\mathbf{a}_{k}\)</span> sobre nuestra nueva base ortonormal, recién calculada, como</p>
<p><span class="math display">\[
\mathbf{R} =\left( \begin{array}{rrrrr}\left&lt; \mathbf{e}_{1} ,\mathbf{a}_{1} \right&gt;  &amp;\left&lt; \mathbf{e}_{1} ,\mathbf{a}_{2} \right&gt;  &amp;\left&lt; \mathbf{e}_{1} ,\mathbf{a}_{3} \right&gt;  &amp;\cdots &amp;\left&lt; \mathbf{e}_{1} ,\mathbf{a}_{n} \right&gt;  \\ 0&amp;\left&lt; \mathbf{e}_{2} ,\mathbf{a}_{2} \right&gt;  &amp;\left&lt; \mathbf{e}_{2} ,\mathbf{a}_{3} \right&gt;  &amp;\cdots &amp;\left&lt; \mathbf{e}_{2} ,\mathbf{a}_{n} \right&gt;  \\ 0&amp;0&amp;\left&lt; \mathbf{e}_{3} ,\mathbf{a}_{3} \right&gt;  &amp;\cdots &amp;\left&lt; \mathbf{e}_{3} ,\mathbf{a}_{n} \right&gt;  \\ \vdots &amp;\vdots &amp;\vdots &amp;\ddots &amp;\vdots \\ 0&amp;0&amp;0&amp;\cdots &amp;\left&lt; \mathbf{e}_{n} ,\mathbf{a}_{n} \right&gt;  \end{array} \right) \tag{7.8}
\]</span></p>
<p>Donde <span class="math inline">\(\left&lt; \mathbf{e}_{i} ,\mathbf{a}_{k} \right&gt;  =\left\Vert \mathbf{u}_{i} \right\Vert\)</span>. Podemos escribir el desarrollo (7.8) en forma matricial como <span class="math inline">\(\mathbf{A}=\mathbf{Q}\mathbf{R}\)</span>, donde <span class="math inline">\(\mathbf{Q}=(\mathbf{e}_{1},...,\mathbf{e}_{n})\)</span> y</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{a}_{1} &amp;=&amp;\left&lt; \mathbf{e}_{1} ,\mathbf{a}_{1} \right&gt;  \mathbf{e}_{1} \\ \mathbf{a}_{2} &amp;=&amp;\left&lt; \mathbf{e}_{1} ,\mathbf{a}_{2} \right&gt;  \mathbf{e}_{1} +\left&lt; \mathbf{e}_{2} ,\mathbf{a}_{2} \right&gt;  \mathbf{e}_{2} \\ \mathbf{a}_{3} &amp;=&amp;\left&lt; \mathbf{e}_{1} ,\mathbf{a}_{3} \right&gt;  \mathbf{e}_{1} +\left&lt; \mathbf{e}_{2} ,\mathbf{a}_{2} \right&gt;  \mathbf{e}_{2} +\left&lt; \mathbf{e}_{3} ,\mathbf{a}_{3} \right&gt;  \mathbf{e}_{3} \\ \vdots &amp;\vdots &amp;\vdots \\ \mathbf{a}_{k} &amp;=&amp;\sum^{k}_{j=1} \left&lt; \mathbf{e}_{j} ,\mathbf{a}_{k} \right&gt;  \mathbf{e}_{j} \end{array} \tag{7.9}
\]</span></p>
<p><strong>Ejemplo 7.3:</strong> Consideremos la matriz</p>
<p><span class="math display">\[
\mathbf{A} =\left( \begin{matrix}1&amp;1&amp;0\\ 1&amp;0&amp;1\\ 0&amp;1&amp;1\end{matrix} \right)  \in \mathbb{R}^{3\times 3} \tag{7.10}
\]</span></p>
<p>Notemos que podemos reescribir la matriz <span class="math inline">\(\mathbf{A}\)</span> con un arreglo de vectores columna del tipo <span class="math inline">\(\mathbf{A}=(\mathbf{a}_{1},\mathbf{a}_{2},\mathbf{a}_{3})\)</span>, donde</p>
<p><span class="math display">\[
\mathbf{a}_{1} =\left( \begin{matrix}1\\ 1\\ 0\end{matrix} \right)  \  ;\  \mathbf{a}_{2} =\left( \begin{matrix}1\\ 0\\ 1\end{matrix} \right)  \  ;\  \mathbf{a}_{3} =\left( \begin{matrix}0\\ 1\\ 1\end{matrix} \right) \tag{7.11}
\]</span></p>
<p>Dado que estos vectores son linealmente independientes en <span class="math inline">\(\mathbb{R}^{3}\)</span>, podemos construir un conjunto ortonormal de los mismos mediante el proceso de Gram-Schmidt. De esta manera tenemos que</p>
<div class="eq-scroll">
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u}_{1} &amp;=&amp;\left( \begin{matrix}1\\ 1\\ 0\end{matrix} \right)  \\ \mathbf{e}_{1} &amp;=&amp;\displaystyle \frac{\left( \begin{matrix}1\\ 1\\ 0\end{matrix} \right)  }{\left\Vert \left( \begin{matrix}1\\ 1\\ 0\end{matrix} \right)  \right\Vert  } =\displaystyle \frac{1}{\sqrt{2} } \left( \begin{matrix}1\\ 1\\ 0\end{matrix} \right)  =\left( \begin{array}{r}\displaystyle \frac{1}{\sqrt{2} } \\ \displaystyle \frac{1}{\sqrt{2} } \\ 0\end{array} \right)  \\ \mathbf{u}_{2} &amp;=&amp;\left( \begin{matrix}1\\ 0\\ 1\end{matrix} \right)  -\displaystyle \frac{1}{\sqrt{2} } \left( \begin{array}{r}\displaystyle \frac{1}{\sqrt{2} } \\ \displaystyle \frac{1}{\sqrt{2} } \\ 0\end{array} \right)  =\left( \begin{array}{r}\displaystyle \frac{1}{2} \\ -\displaystyle \frac{1}{2} \\ 1\end{array} \right)  \\ \mathbf{e}_{2} &amp;=&amp;\displaystyle \frac{\left( \begin{array}{r}\displaystyle \frac{1}{2} \\ -\displaystyle \frac{1}{2} \\ 1\end{array} \right)  }{\left\Vert \left( \begin{array}{r}\displaystyle \frac{1}{2} \\ -\displaystyle \frac{1}{2} \\ 1\end{array} \right)  \right\Vert  } =\displaystyle \frac{1}{\sqrt{3/2} } \left( \begin{array}{r}\displaystyle \frac{1}{2} \\ -\displaystyle \frac{1}{2} \\ 1\end{array} \right)  =\left( \begin{array}{r}\displaystyle \frac{1}{\sqrt{6} } \\ -\displaystyle \frac{1}{\sqrt{6} } \\ \displaystyle \frac{2}{\sqrt{6} } \end{array} \right)  \\ \mathbf{u}_{3} &amp;=&amp;\left( \begin{matrix}1\\ 0\\ 1\end{matrix} \right)  -\displaystyle \frac{1}{\sqrt{2} } \left( \begin{array}{r}\displaystyle \frac{1}{\sqrt{2} } \\ \displaystyle \frac{1}{\sqrt{2} } \\ 0\end{array} \right)  -\displaystyle \frac{1}{\sqrt{6} } \left( \begin{array}{r}\displaystyle \frac{1}{\sqrt{6} } \\ -\displaystyle \frac{1}{\sqrt{6} } \\ \displaystyle \frac{2}{\sqrt{6} } \end{array} \right)  =\left( \begin{array}{r}-\displaystyle \frac{1}{\sqrt{3} } \\ \displaystyle \frac{1}{\sqrt{3} } \\ \displaystyle \frac{1}{\sqrt{3} } \end{array} \right)  \\ \mathbf{e}_{3} &amp;=&amp;\displaystyle \frac{\left( \begin{array}{r}-\displaystyle \frac{1}{\sqrt{3} } \\ \displaystyle \frac{1}{\sqrt{3} } \\ \displaystyle \frac{1}{\sqrt{3} } \end{array} \right)  }{\left\Vert \left( \begin{array}{r}-\displaystyle \frac{1}{\sqrt{3} } \\ \displaystyle \frac{1}{\sqrt{3} } \\ \displaystyle \frac{1}{\sqrt{3} } \end{array} \right)  \right\Vert  } =\left( \begin{array}{r}-\displaystyle \frac{1}{\sqrt{3} } \\ \displaystyle \frac{1}{\sqrt{3} } \\ \displaystyle \frac{1}{\sqrt{3} } \end{array} \right)  \end{array} \tag{7.12}
\]</span></p>
</div>
<p>De esta manera,</p>
<div class="eq-scroll">
<p><span class="math display">\[
\mathbf{Q} =\left( \mathbf{e}_{1} ,\mathbf{e}_{2} ,\mathbf{e}_{2} \right)  =\left( \begin{array}{rrr}\frac{1}{\sqrt{2} } &amp;\frac{1}{\sqrt{6} } &amp;-\frac{1}{\sqrt{3} } \\ \frac{1}{\sqrt{2} } &amp;-\frac{1}{\sqrt{6} } &amp;\frac{1}{\sqrt{3} } \\ 0&amp;\frac{2}{\sqrt{6} } &amp;\frac{1}{\sqrt{3} } \end{array} \right)  \wedge \mathbf{R} =\left( \begin{matrix}\left&lt; \mathbf{u}_{1} ,\mathbf{e}_{1} \right&gt;  &amp;\left&lt; \mathbf{u}_{2} ,\mathbf{e}_{1} \right&gt;  &amp;\left&lt; \mathbf{u}_{3} ,\mathbf{e}_{1} \right&gt;  \\ 0&amp;\left&lt; \mathbf{u}_{2} ,\mathbf{e}_{2} \right&gt;  &amp;\left&lt; \mathbf{u}_{3} ,\mathbf{e}_{2} \right&gt;  \\ 0&amp;0&amp;\left&lt; \mathbf{u}_{3} ,\mathbf{e}_{3} \right&gt;  \end{matrix} \right)  =\left( \begin{array}{rrr}\frac{2}{\sqrt{2} } &amp;\frac{1}{\sqrt{2} } &amp;\frac{1}{\sqrt{2} } \\ 0&amp;\frac{3}{\sqrt{6} } &amp;\frac{1}{\sqrt{6} } \\ 0&amp;0&amp;\frac{2}{\sqrt{3} } \end{array} \right) \tag{7.13}
\]</span></p>
</div>
<p>◼︎</p>
<p><strong>Ejemplo 7.4:</strong> En <strong><font color="darkmagenta">Numpy</font></strong> existe igualmente una implementación de la descomposición QR mediante el uso de la función <code>qr()</code>, también dependiente del módulo <code>numpy.linalg</code>. Sólo se requiere como entrada la matriz de interés:</p>
<div id="208d0e9f" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos una matriz arbitraria de 4x4.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> rng.integers(low<span class="op">=-</span><span class="dv">5</span>, high<span class="op">=</span><span class="dv">5</span>, size<span class="op">=</span>(<span class="dv">4</span>, <span class="dv">4</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostramos nuestra matriz en pantalla.</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>A</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<pre><code>array([[ 0, -4,  3, -1],
       [ 0, -2, -4,  4],
       [ 2,  1, -1,  3],
       [ 0, -1, -1, -3]])</code></pre>
</div>
</div>
<div id="32e52404" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos la descomposición QR de la matriz A.</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>Q, R <span class="op">=</span> np.linalg.qr(A)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="23de5c02" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostramos en pantalla la matriz Q.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>Q</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<pre><code>array([[ 0.        , -0.87287156,  0.48025665, -0.08630637],
       [-0.        , -0.43643578, -0.84751173, -0.3020723 ],
       [-1.        ,  0.        ,  0.        ,  0.        ],
       [-0.        , -0.21821789, -0.22600313,  0.94937007]])</code></pre>
</div>
</div>
<div id="d9da1dc1" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostramos en pantalla la matriz R.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>R</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>array([[-2.        , -1.        ,  1.        , -3.        ],
       [ 0.        ,  4.58257569, -0.65465367, -0.21821789],
       [ 0.        ,  0.        ,  5.05682001, -3.19229419],
       [ 0.        ,  0.        ,  0.        , -3.97009304]])</code></pre>
</div>
</div>
<div id="33a517fd" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comprobamos que la descomposición así definida efectivamente genera la matriz A.</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>np.allclose(A, Q <span class="op">@</span> R)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="11">
<pre><code>True</code></pre>
</div>
</div>
<p>◼︎</p>
</section>
<section id="descomposición-en-valores-singulares." class="level2">
<h2 class="anchored" data-anchor-id="descomposición-en-valores-singulares.">Descomposición en valores singulares.</h2>
<p>Procedemos ahora a revisar el último tópico relativo a la descomposición matricial con uno de los resultados más importantes del álgebra lineal, conocido como <strong>descomposición en valores singulares</strong> (comúnmente llamada SVD, del inglés <em>singular value decomposition</em>). Corresponde a una generalización de la descomposición por autovalores y autovectores (diagonalización) y permite factorizar cualquier matriz <span class="math inline">\(\mathbf{A}\in \mathbb{K}^{m\times n}\)</span>, incluso aunque <span class="math inline">\(\mathbf{A}\)</span> no sea una matriz cuadrada (<span class="math inline">\(m\neq n\)</span>).</p>
<p>Específicamente, la descomposición SVD de una matriz <span class="math inline">\(\mathbf{A}\in \mathbb{K}^{m\times n}\)</span> es una factorización de la forma <span class="math inline">\(\mathbf{A}=\mathbf{U}\mathbf{\Sigma}\mathbf{V}^{\ast}\)</span>, donde <span class="math inline">\(\mathbf{U}\)</span> es una matriz ortogonal de <span class="math inline">\(m\times m\)</span> (es decir, <span class="math inline">\(\mathbf{U}^{\ast}=\mathbf{U}^{-1}\)</span>) con elementos no negativos en su diagonal, $ $ es una matriz ortogonal de <span class="math inline">\(n\times n\)</span> y <span class="math inline">\(\mathbf{V}^{\ast}\)</span> es la matriz transpuesta conjugada de <span class="math inline">\(\mathbf{V}\)</span>. Si <span class="math inline">\(\mathbf{A}\)</span> tiene solo elementos en <span class="math inline">\(\mathbb{R}\)</span>, la descomposición SVD se reduce a una del tipo <span class="math inline">\(\mathbf{A}=\mathbf{U}\mathbf{\Sigma}\mathbf{V}^{\top}\)</span>.</p>
<p>Los elementos diagonales de <span class="math inline">\(\Sigma\)</span>, que denotamos como <span class="math inline">\(\sigma_{i} =\left\{ \psi_{ij} \right\}\)</span>, son determinadas unívocamente por la matriz <span class="math inline">\(\mathbf{A}\)</span> y son llamados <strong>valores singulares</strong> de <span class="math inline">\(\mathbf{A}\)</span>. El número de valores singulares no nulos es igual al rango de la matriz <span class="math inline">\(\mathbf{A}\)</span>. Las columnas de <span class="math inline">\(\mathbf{U}\)</span> y las columnas de <span class="math inline">\(\mathbf{V}\)</span> son llamadas <strong>vectores singulares por la izquierda (siniestrales)</strong> y <strong>vectores singulares por la derecha (dextrales)</strong>, respectivamente, de <span class="math inline">\(\mathbf{A}\)</span>. Entre ambos constituyen dos conjuntos de bases ortonormales <span class="math inline">\(\left\{ \mathbf{u}_{1} ,...,\mathbf{u}_{m} \right\}  \wedge \left\{ \mathbf{v}_{1} ,...,\mathbf{v}_{m} \right\}\)</span>, lo que permite que la descomposición SVD pueda escribirse de forma explícita como</p>
<p><span class="math display">\[
\mathbf{A} =\sum^{r}_{i=1} \sigma_{i} \mathbf{u}_{i} \mathbf{v}^{\ast }_{i} \  ;\  r\leq \rho \left( \mathbf{A} \right)  =\min \left\{ m,n\right\} \tag{7.14}
\]</span></p>
<p>donde <span class="math inline">\(\rho(\mathbf{A})\)</span> es el rango de <span class="math inline">\(\mathbf{A}\)</span>.</p>
<p>La descomposición SVD no es única. Sin embargo, siempre es posible escoger una tal que los valores singulares <span class="math inline">\(\sigma_{i}\)</span> se presenten en un orden decreciente. En este caso, la matriz <span class="math inline">\(\mathbf{\Sigma}\)</span> sí es única y es determinada completamente por <span class="math inline">\(\mathbf{A}\)</span> (pero no <span class="math inline">\(\mathbf{U}\)</span> ni <span class="math inline">\(\mathbf{V}\)</span>).</p>
<p>Antes de comenzar a estudiar en detalle esta descomposición, vamos a definirla por medio de un teorema (aunque, para efectos prácticos, trabajaremos con matrices cuyos elementos son números reales).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Teorema 7.2 – Descomposición en valores singulares
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Sea <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span> una matriz rectangular de rango <span class="math inline">\(\rho(\mathbf{A})\in [0, \min \left\{ m,n\right\}]\)</span>. La descomposición en valores singulares de <span class="math inline">\(\mathbf{A}\)</span> tiene la forma (esquemática) mostrada en la <a href="#fig-svdschematics" class="quarto-xref">Figure&nbsp;1</a></em></p>
<div id="fig-svdschematics" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-svdschematics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig_7_1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-svdschematics-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Un esquema que ilustra la descomposición en valores singulares o SVD
</figcaption>
</figure>
</div>
<p><em>Donde <span class="math inline">\(\mathbf{U}\in \mathbb{R}^{m\times m}\)</span> es una matriz ortogonal con columnas <span class="math inline">\(\mathbf{u}_{i}, i=1,...,m\)</span>, y <span class="math inline">\(\mathbf{V}\in \mathbb{R}^{n\times n}\)</span> es una matriz ortogonal con columnas <span class="math inline">\(\mathbf{v}_{j}, j=1,...,n\)</span>. La matriz de valores singulares <span class="math inline">\(\mathbf{\Sigma } =\left\{ \psi_{ij} \right\}  \in \mathbb{R}^{m\times n}\)</span> tiene las mismas dimensiones que <span class="math inline">\(\mathbf{A}\)</span>, y es tal que <span class="math inline">\(psi_{ij}=0\)</span> para <span class="math inline">\(i\neq j\)</span>.</em></p>
</div>
</div>
<p>Como comentamos en un principio, la matriz de valores singulares <span class="math inline">\(\mathbf{\Sigma}\)</span>, bajo ciertas condiciones, es única, pero requiere cierto nivel de atención. Observemos que <span class="math inline">\(\mathbf{\Sigma}\)</span> tiene la misma dimensión que <span class="math inline">\(\mathbf{A}\)</span>. Esto significa que <span class="math inline">\(\mathbf{\Sigma}\)</span> contiene una submatriz diagonal con los valores singulares de <span class="math inline">\(\mathbf{A}\)</span> con un relleno de ceros en las filas o columnas siguientes (lo que, en computación científica, se conoce como <strong>zero padding</strong>). Específicamente, si <span class="math inline">\(m&gt;n\)</span>, entonces la matriz <span class="math inline">\(\mathbf{\Sigma}\)</span> tiene una estructura diagonal hasta la fila <span class="math inline">\(n\)</span> y luego consiste de vectores fila del tipo <span class="math inline">\(\mathbf{0}^{\top}\)</span> hasta la fila <span class="math inline">\(m\)</span>. Es decir,</p>
<p><span class="math display">\[
\mathbf{\Sigma } =\left( \begin{matrix}\sigma_{1} &amp;0&amp;\cdots &amp;0\\ 0&amp;\sigma_{2} &amp;\cdots &amp;0\\ \vdots &amp;\vdots &amp;\ddots &amp;\vdots \\ 0&amp;0&amp;\cdots &amp;\sigma_{n} \\ \vdots &amp;\vdots &amp;\ddots &amp;\vdots \\ 0&amp;0&amp;\cdots &amp;0\end{matrix} \right) \tag{7.15}
\]</span></p>
<p>Por otro lado, si <span class="math inline">\(m&lt;n\)</span>, entonces la matriz <span class="math inline">\(\mathbf{\Sigma}\)</span> tiene una estructura diagonal hasta la columna <span class="math inline">\(m\)</span> y nula hasta la posición <span class="math inline">\(n\)</span>. Es decir,</p>
<p><span class="math display">\[
\mathbf{\Sigma } =\left( \begin{matrix}\sigma_{1} &amp;0&amp;\cdots &amp;0&amp;\cdots &amp;0\\ 0&amp;\sigma_{2} &amp;\cdots &amp;0&amp;\cdots &amp;0\\ \vdots &amp;\vdots &amp;\ddots &amp;\vdots &amp;\ddots &amp;\vdots \\ 0&amp;0&amp;\cdots &amp;\sigma_{m} &amp;\cdots &amp;0\end{matrix} \right) \tag{7.16}
\]</span></p>
<section id="una-primera-explicación-geométrica." class="level3">
<h3 class="anchored" data-anchor-id="una-primera-explicación-geométrica.">Una primera explicación geométrica.</h3>
<p>La descomposición SVD nos ofrece una interpretación geométrica intuitiva y muy interesante que nos permite describir este procedimiento antes de entrar en el detalle matemático del mismo. En lo que sigue, discutiremos esta descomposición en base a una secuencia de transformaciones lineales aplicadas sobre ciertas bases del conjunto de matrices de interés. Luego, por medio de un ejemplo, aplicaremos estas transformaciones a un conjunto de vectores en ℝ^2, lo que nos permitirá observar el efecto de cada una, en términos geométricos, de manera más clara.</p>
<p>La descomposición SVD de una matriz puede ser interpretada como una que involucra a tres transformaciones lineales asociadas a las correspondientes matrices, digamos del tipo <span class="math inline">\(T:\mathbb{R}^{n}\longrightarrow \mathbb{R}^{n}\)</span>, como se muestra en la <a href="#fig-svdillustr" class="quarto-xref">Figure&nbsp;2</a>. En términos muy generales, la descomposición SVD realiza un cambio de base mediante el uso de la matriz <span class="math inline">\(\mathbf{V}^{\ast}\)</span>, seguido de un escalamiento y aumento (o reducción) de su dimensión mediante el uso de la matriz de valores singulares <span class="math inline">\(\mathbf{\Sigma}\)</span>. Finalmente, se realiza un segundo cambio de base por medio de la matriz <span class="math inline">\(\mathbf{U}\)</span>. Por supuesto, esta secuencia de operaciones guarda mucho más detalles matemáticos que revisaremos más adelante. Pero antes, refinaremos esta interpretación geométrica poniéndole nombre a nuestras operaciones.</p>
<div id="fig-svdillustr" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-svdillustr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig_7_2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-svdillustr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Ilustración de la descomposición de valores singulares <span class="math inline">\(\mathbf{A}=\mathbf{U}\mathbf{\Sigma}\mathbf{V}^{\ast}\)</span> de una matriz de <span class="math inline">\(2\times 2\)</span> con elementos en <span class="math inline">\(\mathbb{R}\)</span>
</figcaption>
</figure>
</div>
<p>Asumamos que disponemos de una matriz de cambio de base asociada a una transformación lineal <span class="math inline">\(T:\mathbb{R}^{n}\longrightarrow \mathbb{R}^{m}\)</span> con respecto a las bases canónicas <span class="math inline">\(\mathbf{e}(n)\)</span> y <span class="math inline">\(\mathbf{e}(m)\)</span>, respectivamente. Además, consideremos dos bases más, digamos <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span>, para <span class="math inline">\(\mathbb{R}^{n}\)</span> y <span class="math inline">\(\mathbb{R}^{m}\)</span>, respectivamente. Entonces:</p>
<ul>
<li><p><strong>(P1):</strong> La matriz <span class="math inline">\(\mathbf{V}\)</span> realiza un cambio de base en el dominio <span class="math inline">\(\mathbb{R}^{n}\)</span> desde la base <span class="math inline">\(\alpha\)</span> (representada por los vectores rojos <span class="math inline">\(\mathbf{v}_{1}\)</span> y <span class="math inline">\(\mathbf{v}_{2}\)</span> en la <a href="#fig-svdillustr" class="quarto-xref">Figure&nbsp;2</a>, panel superior izquierdo) a la base canónica <span class="math inline">\(\mathbf{e}(n)\)</span>. Por lo tanto, podemos escribir <span class="math inline">\(\mathbf{V}^{\ast}=[I]_{\alpha}^{\mathbf{e}(n)}\)</span>, lo que implica que el resultado de esta operación es el alineamiento de estos vectores con los ejes del sistema <span class="math inline">\(\mathbb{R}^{m}\)</span> (lo que se observa en el panel inferior izquierdo de la <a href="#fig-svdillustr" class="quarto-xref">Figure&nbsp;2</a>).</p></li>
<li><p><strong>(P2):</strong> Habiendo cambiado la base de nuestras coordenadas a la referencia canónica de <span class="math inline">\(\mathbb{R}^{m}\)</span>, la matriz <span class="math inline">\(\mathbf{\Sigma}\)</span> escala las nuevas coordenadas con respecto a los valores singulares <span class="math inline">\(\sigma_{i}\)</span> (y añade o quita dimensiones); es decir, <span class="math inline">\(\mathbf{\Sigma}\)</span> es la matriz de cambio de base de <span class="math inline">\(T\)</span> con respecto a <span class="math inline">\(\alpha\)</span> y <span class="math inline">\(\beta\)</span> (es decir, <span class="math inline">\(\mathbf{\Sigma}=[I]_{\alpha}^{\beta}\)</span>), representada por los vectores rojos ubicados en el sistema <span class="math inline">\((\mathbf{e}_{1},\mathbf{e}_{2})\)</span>, los que además son modificados en su longitud. En sistema completo <span class="math inline">\((\mathbf{e}_{1},\mathbf{e}_{2})\)</span> ahora se encuentra inmerso en otro de mayor dimensión, como se observa en el panel inferior derecho de la <a href="#fig-svdillustr" class="quarto-xref">Figure&nbsp;2</a>.</p></li>
<li><p><strong>(P3):</strong> La matriz <span class="math inline">\(\mathbf{U}\)</span> realiza un cambio de base en codominio <span class="math inline">\(\mathbb{R}^{m}\)</span> desde la base <span class="math inline">\(\beta\)</span> a la base canónica <span class="math inline">\(\mathbf{e}(m)\)</span> (es decir, <span class="math inline">\(\mathbf{U}=[I]_{\beta}^{\mathbf{e}(m)}\)</span>), y que se representa por medio de una rotación de los vectores rojos en el gráfico del panel superior derecho de la <a href="#fig-svdillustr" class="quarto-xref">Figure&nbsp;2</a> fuera del sistema <span class="math inline">\((\mathbf{e}_{1},\mathbf{e}_{2})\)</span>.</p></li>
</ul>
<p>La descomposición SVD representa un cambio de base en ambos, dominio y codominio de la transformación lineal <span class="math inline">\(T\)</span>. Esto es distinto a lo que ocurre en la descomposición por autovalores y autovectores (diagonalización), porque ésta opera siempre en el mismo espacio vectorial, donde se aplica siempre un cambio de base que luego se deshace mediante un cambio de base inverso. Lo que hace especial a la descomposición SVD, es que estas dos bases distintas están enlazadas simultáneamente a la matriz de valores singulares <span class="math inline">\(\mathbf{\Sigma}\)</span>.</p>
<p><strong>Ejemplo 7.4:</strong> Consideremos una transformación lineal que aplica una grilla cuadrada de vectores <span class="math inline">\(\mathcal{X}\in \mathbb{R}^{2}\)</span> que caben en una caja de tamaño <span class="math inline">\(2\times 2\)</span> centrada en el origen. Usando la base canónica de <span class="math inline">\(\mathbb{R}^{2}\)</span>, operamos sobre estos vectores usando las siguientes identidades:</p>
<div class="eq-scroll">
<p><span class="math display">\[
\mathbf{A} =\left( \begin{matrix}1&amp;-0.8\\ 0&amp;1\\ 1&amp;0\end{matrix} \right)  =\mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\top } =\left( \begin{matrix}-0.79&amp;0&amp;-0.62\\ 0.38&amp;-0.78&amp;-0.49\\ -0.48&amp;-0.62&amp;0.62\end{matrix} \right)  \left( \begin{matrix}1.62&amp;0\\ 0&amp;1\\ 0&amp;0\end{matrix} \right)  \left( \begin{matrix}-0.78&amp;0.62\\ -0.62&amp;-0.78\end{matrix} \right) \tag{7.17}
\]</span></p>
</div>
<p>Partimos con un conjunto de vectores <span class="math inline">\(\mathcal{X}\)</span> que son representados, en el panel superior izquierdo de la <a href="#fig-svdapply" class="quarto-xref">Figure&nbsp;3</a>, como puntos coloreados (desde magenta a azul) arreglados en una grilla. Luego aplicamos <span class="math inline">\(\mathbf{V}^{\top}\in \mathbb{R}^{2\times 2}\)</span>, lo que genera una rotación de <span class="math inline">\(\mathcal{X}\)</span>, lo que se muestra en el panel inferior izquierdo de la <a href="#fig-svdapply" class="quarto-xref">Figure&nbsp;3</a>. Ahora transformamos estos vectores por medio de la matriz de valores singulares <span class="math inline">\(\mathbf{\Sigma}\)</span> desde el dominio <span class="math inline">\(\mathbb{R}^{2}\)</span> al codominio <span class="math inline">\(\mathbb{R}^{3}\)</span>, como se observa en el panel inferior derecho de la <a href="#fig-svdapply" class="quarto-xref">Figure&nbsp;3</a>. Notemos que todos los vectores <span class="math inline">\(\mathcal{X}\)</span> se ubican en el plano <span class="math inline">\((x_{1},x_{2})\)</span>. La tercera coordenada es siempre igual a cero, y los vectores en el plano <span class="math inline">\((x_{1},x_{2})\)</span> son escalados por los valores singulares presentes en la diagonal de <span class="math inline">\(\mathbf{\Sigma}\)</span>.</p>
<p>La transformación de los vectores <span class="math inline">\(\mathcal{X}\)</span> por medio de <span class="math inline">\(\mathbf{A}\)</span> al codominio <span class="math inline">\(\mathbb{R}^{3}\)</span> se iguala a la transformación de <span class="math inline">\(\mathcal{X}\)</span> por medio de la descomposición <span class="math inline">\(\mathbf{U}\mathbf{\Sigma}\mathbf{V}^{\top}\)</span>, donde <span class="math inline">\(\mathbf{U}\)</span> aplica una rotación en el codominio <span class="math inline">\(\mathbb{R}^{3}\)</span>, de manera tal que los vectores sobre los cuales operamos mediante esta transformación ya no están restringidos al sistema <span class="math inline">\((x_{1},x_{2})\)</span>, aunque siguen residiendo en un plano, como se observa en el panel superior derecho de la <a href="#fig-svdapply" class="quarto-xref">Figure&nbsp;3</a>.</p>
<div id="fig-svdapply" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-svdapply-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig_7_3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:90.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-svdapply-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Esquema geométrico que interpreta la aplicación de la descomposición de valores singulares en el ejemplo (7.4)
</figcaption>
</figure>
</div>
<p>◼︎</p>
</section>
<section id="construcción-de-la-descomposición-en-valores-singulares." class="level3">
<h3 class="anchored" data-anchor-id="construcción-de-la-descomposición-en-valores-singulares.">Construcción de la descomposición en valores singulares.</h3>
<p>A continuación, discutiremos las <strong>condiciones de existencia</strong> de la descomposición en valores singulares y mostraremos cómo calcularla en detalle. Esta descomposición comparte ciertas similitudes con la <strong>diagonalización de matrices hermíticas</strong>, ya que</p>
<p><span class="math display">\[
\mathbf{S} =\mathbf{S}^{\top } =\mathbf{P} \mathbf{D} \mathbf{P}^{-1} \tag{7.18}
\]</span></p>
<p>Donde <span class="math inline">\(\mathbf{S}\in \mathbb{R}^{n\times n}\)</span> es una matriz hermítica. La correspondiente descomposición en valores singulares es</p>
<p><span class="math display">\[
\mathbf{S} =\mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\ast } \tag{7.19}
\]</span></p>
<p>Si ponemos <span class="math inline">\(\mathbf{U}=\mathbf{P}=\mathbf{V}\)</span> y <span class="math inline">\(\mathbf{D}=\mathbf{\Sigma}\)</span>, podemos concluir que la descomposición en valores singulares de matrices hermíticas es equivalente a su descomposición diagonal.</p>
<p>A continuación, discutiremos las condiciones bajo las cuales el Teorema (7.2) se cumple y cómo construimos la descomposición SVD. El cálculo de esta descomposición para una matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span> es equivalente a encontrar dos conjuntos de bases ortonormales <span class="math inline">\(\alpha =\left\{ \mathbf{u}_{1} ,...,\mathbf{u}_{m} \right\}  \wedge \beta =\left\{ \mathbf{v}_{1} ,...,\mathbf{v}_{n} \right\}\)</span> relativos al dominio <span class="math inline">\(\mathbb{R}^{m}\)</span> y al codominio <span class="math inline">\(\mathbb{R}^{n}\)</span>, respectivamente. A partir de estas bases, construimos las matrices <span class="math inline">\(\mathbf{U}\)</span> y <span class="math inline">\(\mathbf{V}\)</span>. Para ello, será necesario que establezcamos primero un teorema esencial en la construcción de la descomposición SVD.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Teorema 7.3
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Sea <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span> una matriz no singular. Entonces siempre podremos definir una matriz simétrica y semi-definida positiva <span class="math inline">\(\mathbf{S}\in \mathbb{R}^{n\times n}\)</span>, a partir de <span class="math inline">\(\mathbf{A}\)</span>, como</em></p>
<p><span class="math display">\[
\mathbf{S} :=\mathbf{A}^{\top } \mathbf{A} \tag{7.20}
\]</span></p>
</div>
</div>
<p>Nuestro plan es comenzar construyendo el conjunto ortonormal de <strong>vectores singulares por la derecha</strong> <span class="math inline">\(\beta =\left\{ \mathbf{v}_{1} ,...,\mathbf{v}_{n} \right\}  \in \mathbb{R}^{n}\)</span>. Luego construiremos el conjunto de <strong>vectores singulares por la izquierda</strong> <span class="math inline">\(\alpha =\left\{ \mathbf{u}_{1} ,...,\mathbf{u}_{m} \right\}  \in \mathbb{R}^{m}\)</span>. A continuación, enlazaremos ambos conjuntos con el requerimiento de <strong>la ortogonalidad de <span class="math inline">\(\beta\)</span> se preserve conforme la transformación de <span class="math inline">\(\mathbf{A}\)</span></strong>. Esto último es importante porque sabemos de antemano que las imágenes <span class="math inline">\(\mathbf{A}\mathbf{v}_{i}\)</span> conforman un conjunto ortogonal de vectores. Luego normalizaremos estas imágenes por medio de factores de escalamiento, los que, por supuesto, resultarán ser los <strong>valores singulares</strong> de <span class="math inline">\(\mathbf{A}\)</span>.</p>
<p>Partimos entonces construyendo los vectores singulares por la derecha. El teorema de descomposición espectral nos dice que los autovectores de una matriz simétrica conforman una base ortonormal, lo que implica, por supuesto, que dicha matriz es diagonalizable. Además, del teorema (7.3), sabemos que siempre podemos construir una matriz simétrica y semi-definida positiva <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\in \mathbb{R}^{n\times n}\)</span> a partir de cualquier matriz rectangular. De esta manera, podemos diagonalizar <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span> y obtener</p>
<p><span class="math display">\[
\mathbf{A}^{\top } \mathbf{A} =\mathbf{P} \mathbf{D} \mathbf{P}^{\top } =\mathbf{P} \left( \begin{matrix}\lambda_{1} &amp;\cdots &amp;0\\ \vdots &amp;\ddots &amp;\vdots \\ 0&amp;\cdots &amp;\lambda_{n} \end{matrix} \right)  \mathbf{P}^{\top } \tag{7.21}
\]</span></p>
<p>Donde <span class="math inline">\(\mathbf{P}\)</span> es una matriz ortogonal que está compuesta por una base ortonormal de autovectores. Los escalares <span class="math inline">\(\lambda_{1}, ..., \lambda_{n}\)</span> son los autovalores de <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span>. Asumamos entonces que la descomposición en valores singulares de <span class="math inline">\(\mathbf{A}\)</span> existe y apliquemos el teorema (7.2) a la ecuación (7.21). De esta manera, obtenemos</p>
<p><span class="math display">\[
\mathbf{A}^{\top } \mathbf{A} =\left( \mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\top } \right)^{\top }  \left( \mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\top } \right)  =\mathbf{V} \mathbf{\Sigma }^{\top } \mathbf{U}^{\top } \mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\top } \tag{7.22}
\]</span></p>
<p>Como <span class="math inline">\(\mathbf{U}\)</span> y <span class="math inline">\(\mathbf{V}\)</span> son matrices ortogonales, tenemos que <span class="math inline">\(\mathbf{U}^{\top}\mathbf{U}=\mathbf{I}_{m}\)</span>. Por lo tanto,</p>
<p><span class="math display">\[
\mathbf{A}^{\top } \mathbf{A} =\mathbf{V} \mathbf{\Sigma }^{\top } \mathbf{\Sigma } \mathbf{V}^{\top } =\mathbf{V} \left( \begin{matrix}\sigma^{2}_{1} &amp;\cdots &amp;0\\ \vdots &amp;\ddots &amp;\vdots \\ 0&amp;\cdots &amp;\sigma^{2}_{n} \end{matrix} \right)  \mathbf{V}^{\top } \tag{7.23}
\]</span></p>
<p>Si comparamos las ecuaciones (7.23) y (7.21), podemos darnos cuenta que</p>
<p><span class="math display">\[
\mathbf{V}^{\top } =\mathbf{P}^{\top } \wedge \sigma^{2}_{i} =\lambda_{i} \tag{7.24}
\]</span></p>
<p>Por lo tanto, los autovectores de <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span> que componen <span class="math inline">\(\mathbf{P}\)</span> son los vectores singulares derechos <span class="math inline">\(\mathbf{V}\)</span> de <span class="math inline">\(\mathbf{A}\)</span>, mientras que los autovalores de <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span> son iguales al cuadrado de los valores singulares de <span class="math inline">\(\mathbf{A}\)</span> (y que se corresponden con los elementos no nulos de la matriz <span class="math inline">\(\mathbf{\Sigma}\)</span>. Para obtener los vectores singulares por la izquierda que componen <span class="math inline">\(\mathbf{U}\)</span>, seguimos un procedimiento similar. Partimos calculando la descomposición en valores singulares de la matriz simétrica <span class="math inline">\(\mathbf{A}\mathbf{A}^{\top}\in \mathbb{R}^{m\times m}\)</span>. En este caso, obtenemos</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{A} \mathbf{A}^{\top } &amp;=&amp;\left( \mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\top } \right)  \left( \mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\top } \right)^{\top }  \\ &amp;=&amp;\mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\top } \mathbf{V} \mathbf{\Sigma }^{\top } \mathbf{U}^{\top } \\ &amp;=&amp;\mathbf{U} \left( \begin{matrix}\sigma^{2}_{1} &amp;\cdots &amp;0\\ \vdots &amp;\ddots &amp;\vdots \\ 0&amp;\cdots &amp;\sigma^{2}_{n} \end{matrix} \right)  \mathbf{U}^{\top } \end{array} \tag{7.25}
\]</span></p>
<p>El teorema de descomposición espectral nos dice que <span class="math inline">\(\mathbf{A}\mathbf{A}^{\top} = \mathbf{S}\mathbf{D}\mathbf{S}^{\top}\)</span> es diagonalizable y que podemos encontrar una base ortonormal de autovectores de <span class="math inline">\(\mathbf{A}\mathbf{A}^{\top}\)</span>, los que están contenidos en <span class="math inline">\(\mathbf{S}\)</span>. Los autovectores ortonormales de <span class="math inline">\(\mathbf{A}\mathbf{A}^{\top}\)</span> son los vectores singulares por la izquierda que constituyen <span class="math inline">\(\mathbf{U}\)</span> y conforman una base ortonormal en el codominio de la descomposició SVD.</p>
<p>Lo anterior deja abierta la pregunta relativa a la estructura de la matriz <span class="math inline">\(\mathbf{\Sigma}\)</span>. Dado que <span class="math inline">\(\mathbf{A}\mathbf{A}^{\top}\)</span> y <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span> tienen los mismos autovalores no nulos, las entradas no nulas de las matrices <span class="math inline">\(\mathbf{\Sigma}\)</span> en ambas descomposiciones SVD (para <span class="math inline">\(\mathbf{A}\mathbf{A}^{\top}\)</span> y <span class="math inline">\(\mathbf{A}\mathbf{A}^{\top}\)</span> deben ser las mismas.</p>
<p>El último paso es unir todo lo que hemos hecho hasta ahora. Tenemos un conjunto ortonormal de vectores singulares por la derecha en la matriz <span class="math inline">\(\mathbf{V}\)</span> y, para finalizar la construcción de la factorización SVD, debemos unirlos a los vectores singulares por la izquierda que componen la matriz <span class="math inline">\(\mathbf{U}\)</span>. Para lograr esto, usamos el hecho de que las imágenes de los vectores <span class="math inline">\(\mathbf{v}_{1},...,\mathbf{v}_{n}\)</span> bajo <span class="math inline">\(\mathbf{A}\)</span> tienen que ser, también, ortogonales. En ese caso, necesitamos que el producto interno entre <span class="math inline">\(\mathbf{A}\mathbf{v}_{i}\)</span> y <span class="math inline">\(\mathbf{A}\mathbf{v}_{j}\)</span> sea nulo para <span class="math inline">\(i\neq j\)</span>. De este modo, tenemos que</p>
<p><span class="math display">\[
\left( \mathbf{A} \mathbf{v}_{i} \right)^{\top }  \left( \mathbf{A} \mathbf{v}_{j} \right)  =\mathbf{v}^{\top }_{i} \left( \mathbf{A}^{\top } \mathbf{A} \right)  \mathbf{v}_{j} =\mathbf{v}^{\top }_{i} \left( \lambda_{j} \mathbf{v}_{j} \right)  =\lambda_{j} \mathbf{v}^{\top }_{i} \mathbf{v}_{j} =0 \tag{7.26}
\]</span></p>
<p>Para el caso <span class="math inline">\(m\geq r\)</span>, se tiene que <span class="math inline">\(\left\{ \mathbf{A} \mathbf{v}_{1} ,...,\mathbf{A} \mathbf{v}_{r} \right\}\)</span> es una base para un subespacio <span class="math inline">\(r\)</span>-dimensional de <span class="math inline">\(\mathbb{R}^{m}\)</span>.</p>
<p>Para completar la construcción de la descomposición SVD, necesitamos vectores singulares por la izquierda que sean ortonormales. Por lo tanto, normalizamos las imágenes de los vectores singulares por la derecha <span class="math inline">\(\mathbf{A} \mathbf{v}_{i}\)</span>, obteniendo</p>
<p><span class="math display">\[
\mathbf{u}_{i} :=\frac{\mathbf{A} \mathbf{v}_{i} }{\left\Vert \mathbf{A} \mathbf{v}_{i} \right\Vert  } =\frac{1}{\sqrt{\lambda_{i} } } \mathbf{A} \mathbf{v}_{i} =\frac{1}{\sigma_{i} } \mathbf{A} \mathbf{v}_{i} \tag{7.27}
\]</span></p>
<p>Por lo tanto, los autovectores de <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span>, que ya sabemos que son los vectores singulares por la derecha <span class="math inline">\(\mathbf{v}_{i}\)</span>, y sus imágenes normalizadas bajo <span class="math inline">\(\mathbf{A}\)</span>, los vectores singulares por la izquierda <span class="math inline">\(\mathbf{u}_{i}\)</span>, conforman dos bases ortonormales consistentes que están conectadas por la matriz de valores singulares <span class="math inline">\(\mathbf{\Sigma}\)</span>.</p>
<p>Vamos a reorganizar la ecuación (7.27) para obtener la <strong>ecuación de valores singulares</strong></p>
<p><span class="math display">\[
\mathbf{A} \mathbf{v}_{i} =\sigma_{i} \mathbf{u}_{i} \  ;\  i=1,...,r \tag{7.28}
\]</span></p>
<p>Para <span class="math inline">\(n&lt;m\)</span>, la ecuación (7.28) se cumple únicamente para <span class="math inline">\(i\leq n\)</span>, pero no nos dice nada acerca de los vectores <span class="math inline">\(\mathbf{u}_{i}\)</span> para <span class="math inline">\(i&gt;n\)</span>. Sin embargo, por construcción, sabemos que dichos vectores son ortonormales. Por el contrario, para <span class="math inline">\(m&lt;n\)</span>, la ecuación (7.28) se cumple únicamente para <span class="math inline">\(i\geq m\)</span>. Para <span class="math inline">\(i&gt;m\)</span>, tenemos que <span class="math inline">\(\mathbf{A}\mathbf{v}_{i}=0\)</span> y aún sabemos que los vectores <span class="math inline">\(\mathbf{v}_{i}\)</span> conforman un conjunto ortonormal. Esto significa que la descomposición SVD también nos provee de una base ortornomal para <span class="math inline">\(\ker(\mathbf{A})\)</span> (es decir, el conjunto de vectores <span class="math inline">\(\mathbf{x}\)</span> tales que <span class="math inline">\(\mathbf{A}\mathbf{x}=\mathbf{0}\)</span>).</p>
<p>Uniendo los vectores <span class="math inline">\(\mathbf{v}_{i}\)</span> como columnas de <span class="math inline">\(\mathbf{V}\)</span> y los vectores <span class="math inline">\(\mathbf{u}_{i}\)</span> como columnas de <span class="math inline">\(\mathbf{U}\)</span>, obtenemos</p>
<p><span class="math display">\[
\mathbf{A} \mathbf{v} =\mathbf{U} \mathbf{\Sigma } \tag{7.29}
\]</span></p>
<p>Donde <span class="math inline">\(\mathbf{\Sigma }\)</span> tiene la misma dimensión que <span class="math inline">\(\mathbf{A}\)</span> y una estructura diagonal para las filas 1 a <span class="math inline">\(r\)</span>. Por lo tanto, multiplicando esta expresión por la derecha por <span class="math inline">\(\mathbf{V}^{\top}\)</span>, obtenemos <span class="math inline">\(\mathbf{A}=\mathbf{U}\mathbf{\Sigma }\mathbf{V}^{\top}\)</span>, que resulta ser la descomposición SVD de <span class="math inline">\(\mathbf{A}\)</span>.</p>
<p><strong>Ejemplo 7.5:</strong> Vamos a determinar la descomposición en valores singulares de la matriz <span class="math inline">\(\mathbf{A}\)</span> definida como</p>
<p><span class="math display">\[
\mathbf{A} =\left( \begin{matrix}4&amp;11&amp;14\\ 8&amp;7&amp;-2\end{matrix} \right) \tag{7.30}
\]</span></p>
<p>Siguiendo el proceso de construcción de la descomposición SVD visto previamente, sabemos que el primer paso es determinar los autovalores del producto <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span>. En este caso, como</p>
<p><span class="math display">\[
\mathbf{A}^{\top } \mathbf{A} =\left( \begin{matrix}80&amp;100&amp;40\\ 100&amp;170&amp;140\\ 40&amp;140&amp;200\end{matrix} \right) \tag{7.31}
\]</span></p>
<p>y se tiene que el polinomio característico de esta matriz es <span class="math inline">\(P_{\mathbf{A}^{\top } \mathbf{A} }\left( \lambda \right)  =\det \left( \mathbf{A}^{\top } \mathbf{A} -\lambda \mathbf{I}_{3} \right)  =\lambda \left( \lambda -360\right)  \left( \lambda -90\right)\)</span>, lo que implica que sus autovalores son <span class="math inline">\(\lambda_{1} =360,\lambda_{2} =90\)</span> y <span class="math inline">\(\lambda_{3}=0\)</span>. Por lo tanto, los valores singulares de <span class="math inline">\(\mathbf{A}\)</span> son <span class="math inline">\(\sigma_{1} =6\sqrt{10} ,\sigma_{2} =3\sqrt{10}\)</span> y <span class="math inline">\(\sigma_{3}=0\)</span>. Buscaremos ahora una base ortonormal de autovectores para <span class="math inline">\(\mathbf{A}^{\top } \mathbf{A}\)</span>. Para ello, determinamos los autoespacios respectivos como sigue,</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u} \in \left( \mathbb{R}^{3\times 1} \right)_{\lambda }  &amp;\Longleftrightarrow &amp;\mathbf{u} \in \mathbb{R}^{3\times 1} \wedge \left( \mathbf{A}^{\top } \mathbf{A} \right)  \mathbf{u} =\lambda \mathbf{u} \\ &amp;\Longleftrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \left( \begin{matrix}80&amp;100&amp;40\\ 100&amp;170&amp;140\\ 40&amp;140&amp;200\end{matrix} \right)  \left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  =\left( \begin{matrix}\lambda x\\ \lambda y\\ \lambda z\end{matrix} \right)  \\ &amp;\Longleftrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \begin{cases}\begin{array}{rcl}80x+100y+40z&amp;=&amp;\lambda x\\ 100x+170y+140z&amp;=&amp;\lambda y\\ 40x+140y+200z&amp;=&amp;\lambda z\end{array} &amp;\end{cases} \end{array} \tag{7.32}
\]</span></p>
<p>Para <span class="math inline">\(\lambda_{1}=360\)</span>:</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u} \in \left( \mathbb{R}^{3\times 1} \right)_{\lambda =360}  &amp;\Longleftrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \begin{cases}\begin{array}{rcl}80x+100y+40z&amp;=&amp;360x\\ 100x+170y+140z&amp;=&amp;360y\\ 40x+140y+200z&amp;=&amp;360z\end{array} &amp;\end{cases} \\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge y=2x\wedge z=2x\\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ 2x\\ 2x\end{matrix} \right)  =x\left( \begin{matrix}1\\ 2\\ 2\end{matrix} \right)  \\ &amp;\Longrightarrow &amp;\left( \mathbb{R}^{3\times 1} \right)_{\lambda =360}  =\left&lt; \left\{ \left( \begin{matrix}1\\ 2\\ 2\end{matrix} \right)  \right\}  \right&gt;  \end{array} \tag{7.33}
\]</span></p>
<p>Para <span class="math inline">\(\lambda_{2}=90\)</span>:</p>
<div class="eq-scroll">
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u} \in \left( \mathbb{R}^{3\times 1} \right)_{\lambda =90}  &amp;\Longleftrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \begin{cases}\begin{array}{rcl}80x+100y+40z&amp;=&amp;90x\\ 100x+170y+140z&amp;=&amp;90y\\ 40x+140y+200z&amp;=&amp;90z\end{array} &amp;\end{cases} \\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge 2z=-2x\wedge 2z=-y\\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}-2x\\ -x\\ 2x\end{matrix} \right)  =x\left( \begin{matrix}-2\\ -1\\ 2\end{matrix} \right)  \\ &amp;\Longrightarrow &amp;\left( \mathbb{R}^{3\times 1} \right)_{\lambda =90}  =\left&lt; \left\{ \left( \begin{matrix}-2\\ -1\\ 2\end{matrix} \right)  \right\}  \right&gt;  \end{array} \tag{7.34}
\]</span></p>
</div>
<p>Finalmente, para <span class="math inline">\(\lambda_{3}=0\)</span></p>
<div class="eq-scroll">
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u} \in \left( \mathbb{R}^{3\times 1} \right)_{\lambda =0}  &amp;\Longleftrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \begin{cases}\begin{array}{rcl}80x+100y+40z&amp;=&amp;0x\\ 100x+170y+140z&amp;=&amp;0y\\ 40x+140y+200z&amp;=&amp;0z\end{array} &amp;\end{cases} \\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge z=2x\wedge z=-2y\\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}2x\\ -2x\\ x\end{matrix} \right)  =x\left( \begin{matrix}2\\ -2\\ 1\end{matrix} \right)  \\ &amp;\Longrightarrow &amp;\left( \mathbb{R}^{3\times 1} \right)_{\lambda =90}  =\left&lt; \left\{ \left( \begin{matrix}2\\ -2\\ 1\end{matrix} \right)  \right\}  \right&gt;  \end{array} \tag{7.35}
\]</span></p>
</div>
<p>Por lo tanto, una base ortonormal de autovectores para <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span> es</p>
<div class="eq-scroll">
<p><span class="math display">\[
\alpha =\left\{ \frac{\left( \begin{matrix}1\\ 2\\ 2\end{matrix} \right)  }{\left\Vert \left( \begin{matrix}1\\ 2\\ 2\end{matrix} \right)  \right\Vert  } ,\frac{\left( \begin{matrix}-2\\ -1\\ 2\end{matrix} \right)  }{\left\Vert \left( \begin{matrix}-2\\ -1\\ 2\end{matrix} \right)  \right\Vert  } ,\frac{\left( \begin{matrix}2\\ -2\\ 1\end{matrix} \right)  }{\left\Vert \left( \begin{matrix}2\\ -2\\ 1\end{matrix} \right)  \right\Vert  } \right\}  =\left\{ \frac{1}{\sqrt{9} } \left( \begin{matrix}1\\ 2\\ 2\end{matrix} \right)  ,\frac{1}{\sqrt{9} } \left( \begin{matrix}-2\\ -1\\ 2\end{matrix} \right)  ,\frac{1}{\sqrt{9} } \left( \begin{matrix}2\\ -2\\ 1\end{matrix} \right)  \right\}  =\left\{ \frac{1}{3} \left( \begin{matrix}1\\ 2\\ 2\end{matrix} \right)  ,\frac{1}{3} \left( \begin{matrix}-2\\ -1\\ 2\end{matrix} \right)  ,\frac{1}{3} \left( \begin{matrix}2\\ -2\\ 1\end{matrix} \right)  \right\} \tag{7.36}
\]</span></p>
</div>
<p>Calculamos ahora <span class="math inline">\(\mathbf{A}\mathbf{v}_{i}\)</span> para <span class="math inline">\(i=1,2,3\)</span> como sigue,</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{A} \mathbf{v}_{1} &amp;=&amp;\left( \begin{matrix}4&amp;11&amp;14\\ 8&amp;7&amp;-2\end{matrix} \right)  \left( \begin{matrix}1/3\\ 2/3\\ 2/3\end{matrix} \right)  =\left( \begin{matrix}18\\ 6\end{matrix} \right)  \\ \mathbf{A} \mathbf{v}_{2} &amp;=&amp;\left( \begin{matrix}4&amp;11&amp;14\\ 8&amp;7&amp;-2\end{matrix} \right)  \left( \begin{matrix}-2/3\\ -1/3\\ 2/3\end{matrix} \right)  =\left( \begin{matrix}3\\ -9\end{matrix} \right)  \\ \mathbf{A} \mathbf{v}_{3} &amp;=&amp;\left( \begin{matrix}4&amp;11&amp;14\\ 8&amp;7&amp;-2\end{matrix} \right)  \left( \begin{matrix}2/3\\ -2/3\\ 1/3\end{matrix} \right)  =\left( \begin{matrix}0\\ 0\end{matrix} \right)  \end{array} \tag{7.37}
\]</span></p>
<p>Como hay dos valores singulares no nulos, tenemos</p>
<div class="eq-scroll">
<p><span class="math display">\[
\mathbf{u}_{1} =\displaystyle \frac{1}{\sigma_{1} } \mathbf{A} \mathbf{v}_{1} =\displaystyle \frac{1}{6\sqrt{10} } \left( \begin{matrix}18\\ 6\end{matrix} \right)  =\left( \begin{array}{r}\displaystyle \frac{3}{\sqrt{10} } \\ \displaystyle \frac{1}{\sqrt{10} } \end{array} \right)  \  ;\  \mathbf{u}_{2} =\displaystyle \frac{1}{\sigma_{2} } \mathbf{A} \mathbf{v}_{2} =\displaystyle \frac{1}{3\sqrt{10} } \left( \begin{matrix}3\\ -9\end{matrix} \right)  =\left( \begin{array}{r}\displaystyle \frac{1}{\sqrt{10} } \\ -\displaystyle \frac{3}{\sqrt{10} } \end{array} \right) \tag{7.38}
\]</span></p>
</div>
<p>Notemos que <span class="math inline">\(\beta=\left\{ \mathbf{u}_{1} ,\mathbf{u}_{2} \right\}\)</span> es una base ortonormal para <span class="math inline">\(\mathbb{R}^{2}\)</span>. De esta manera, la descomposición en valores singulares de <span class="math inline">\(\mathbf{A}\)</span> es</p>
<p><span class="math display">\[
\mathbf{A} =\underbrace{\left( \begin{array}{rr}\displaystyle \frac{3}{\sqrt{10} } &amp;\displaystyle \frac{1}{\sqrt{10} } \\ \displaystyle \frac{1}{\sqrt{10} } &amp;-\displaystyle \frac{3}{\sqrt{10} } \end{array} \right)  }_{\mathbf{U} } \underbrace{\left( \begin{matrix}6\sqrt{10} &amp;0&amp;0\\ 0&amp;3\sqrt{10} &amp;0\end{matrix} \right)  }_{\mathbf{\Sigma } } \underbrace{\left( \begin{array}{rrr}1/3&amp;2/3&amp;2/3\\ -2/3&amp;-1/3&amp;2/3\\ 2/3&amp;-2/3&amp;1/3\end{array} \right)  }_{\mathbf{V}^{\top } } \tag{7.39}
\]</span> ◼︎</p>
<p><strong>Ejemplo 7.6:</strong> Vamos a encontrar la descomposición en valores singulares de la matriz</p>
<p><span class="math display">\[
\mathbf{A} =\left( \begin{matrix}1&amp;0&amp;1\\ -2&amp;1&amp;0\end{matrix} \right) \tag{7.40}
\]</span></p>
<p>En efecto, primero construimos la matriz <span class="math inline">\(\mathbf{A}^{\top} \mathbf{A}\)</span> como sigue,</p>
<p><span class="math display">\[
\mathbf{A}^{\top } \mathbf{A} =\left( \begin{matrix}1&amp;-2\\ 0&amp;1\\ 1&amp;0\end{matrix} \right)  \left( \begin{matrix}1&amp;0&amp;1\\ -2&amp;1&amp;0\end{matrix} \right)  =\left( \begin{matrix}5&amp;-2&amp;1\\ -2&amp;1&amp;0\\ 1&amp;0&amp;1\end{matrix} \right) \tag{7.41}
\]</span></p>
<p>Queremos pues diagonalizar <span class="math inline">\(\mathbf{A}^{\top } \mathbf{A}\)</span>. Partimos calculando su polinomio característico,</p>
<p><span class="math display">\[
P_{\mathbf{A}^{\top } \mathbf{A} }\left( \lambda \right)  =\left( \begin{matrix}5-\lambda &amp;-2&amp;1\\ -2&amp;1-\lambda &amp;0\\ 1&amp;0&amp;1-\lambda \end{matrix} \right)  =\lambda \left( \lambda -6\right)  \left( \lambda -1\right) \tag{7.42}
\]</span></p>
<p>Por lo que los autovalores de <span class="math inline">\(\mathbf{A}^{\top } \mathbf{A}\)</span> son <span class="math inline">\(\lambda_{1}=6,\lambda_{2}=1\)</span> y <span class="math inline">\(\lambda_{3}=0\)</span>. De esta manera, los valores singulares de <span class="math inline">\(\mathbf{A}^{\top } \mathbf{A}\)</span> son <span class="math inline">\(\sigma_{1}=\sqrt{6}, \sigma_{2}=1\)</span> y <span class="math inline">\(\sigma_{3}=0\)</span>. Debemos buscar ahora una base ortonormal de autovectores para <span class="math inline">\(\mathbf{A}^{\top } \mathbf{A}\)</span> a partir del cálculo de sus autoespacios. De este modo tenemos que</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u} \in \left( \mathbb{R}^{3\times 1} \right)_{\lambda }  &amp;\Longleftrightarrow &amp;\mathbf{u} \in \mathbb{R}^{3\times 1} \wedge \left( \mathbf{A}^{\top } \mathbf{A} \right)  \mathbf{u} =\lambda \mathbf{u} \\ &amp;\Longleftrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \left( \begin{matrix}5&amp;-2&amp;1\\ -2&amp;1&amp;0\\ 1&amp;0&amp;1\end{matrix} \right)  \left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  =\left( \begin{matrix}\lambda x\\ \lambda y\\ \lambda z\end{matrix} \right)  \\ &amp;\Longleftrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \begin{cases}\begin{array}{rcl}5x-2y+z&amp;=&amp;\lambda x\\ -2x+y&amp;=&amp;\lambda y\\ x+z&amp;=&amp;\lambda z\end{array} &amp;\end{cases} \end{array} \tag{7.43}
\]</span></p>
<p>Luego, para <span class="math inline">\(\lambda_{1}=6\)</span>,</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u} \in \left( \mathbb{R}^{3\times 1} \right)_{\lambda =6}  &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \begin{array}{rcl}5x-2y+z&amp;=&amp;6x\\ -2x+y&amp;=&amp;6y\\ x+z&amp;=&amp;6z\end{array} \\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge x=5z\wedge y=-2z\\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}5z\\ -2z\\ z\end{matrix} \right)  =z\left( \begin{matrix}5\\ -2\\ 1\end{matrix} \right)  \\ &amp;\Longrightarrow &amp;\left( \mathbb{R}^{3\times 1} \right)_{\lambda =6}  =\left&lt; \left\{ \left( \begin{matrix}5\\ -2\\ 1\end{matrix} \right)  \right\}  \right&gt;  \end{array} \tag{7.44}
\]</span></p>
<p>Además, para <span class="math inline">\(\lambda_{2}=1\)</span></p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u} \in \left( \mathbb{R}^{3\times 1} \right)_{\lambda =1}  &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \begin{array}{rcl}5x-2y+z&amp;=&amp;x\\ -2x+y&amp;=&amp;y\\ x+z&amp;=&amp;z\end{array} \\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge x=0\wedge z=2y\\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}0\\ y\\ 2y\end{matrix} \right)  =y\left( \begin{matrix}0\\ 1\\ 2\end{matrix} \right)  \\ &amp;\Longrightarrow &amp;\left( \mathbb{R}^{3\times 1} \right)_{\lambda =1}  =\left&lt; \left\{ \left( \begin{matrix}0\\ 1\\ 2\end{matrix} \right)  \right\}  \right&gt;  \end{array} \tag{7.45}
\]</span></p>
<p>Finalmente, para <span class="math inline">\(\lambda_{3}=0\)</span>,</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{u} \in \left( \mathbb{R}^{3\times 1} \right)_{\lambda =0}  &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge \begin{array}{rcl}5x-2y+z&amp;=&amp;0x\\ -2x+y&amp;=&amp;0y\\ x+z&amp;=&amp;0z\end{array} \\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}x\\ y\\ z\end{matrix} \right)  \wedge y=-2z\wedge x=-z\\ &amp;\Longrightarrow &amp;\mathbf{u} =\left( \begin{matrix}-z\\ -2z\\ z\end{matrix} \right)  =z\left( \begin{matrix}-1\\ -2\\ 1\end{matrix} \right)  \\ &amp;\Longrightarrow &amp;\left( \mathbb{R}^{3\times 1} \right)_{\lambda =0}  =\left&lt; \left\{ \left( \begin{matrix}-1\\ -2\\ 1\end{matrix} \right)  \right\}  \right&gt;  \end{array} \tag{7.46}
\]</span></p>
<p>Por lo tanto, una base ortonormal de autovectores para <span class="math inline">\(\mathbf{A}^{\top}\mathbf{A}\)</span> es</p>
<div class="eq-scroll">
<p><span class="math display">\[
\alpha =\left\{ \frac{\left( \begin{matrix}5\\ -2\\ 1\end{matrix} \right)  }{\left\Vert \left( \begin{matrix}5\\ -2\\ 1\end{matrix} \right)  \right\Vert  } ,\frac{\left( \begin{matrix}0\\ 1\\ 2\end{matrix} \right)  }{\left\Vert \left( \begin{matrix}0\\ 1\\ 2\end{matrix} \right)  \right\Vert  } ,\frac{\left( \begin{matrix}-1\\ -2\\ 1\end{matrix} \right)  }{\left\Vert \left( \begin{matrix}-1\\ -2\\ 1\end{matrix} \right)  \right\Vert  } \right\}  =\left\{ \frac{1}{\sqrt{30} } \left( \begin{matrix}5\\ -2\\ 1\end{matrix} \right)  ,\frac{1}{\sqrt{5} } \left( \begin{matrix}0\\ 1\\ 2\end{matrix} \right)  ,\frac{1}{\sqrt{6} } \left( \begin{matrix}-1\\ -2\\ 1\end{matrix} \right)  \right\} \tag{7.47}
\]</span></p>
</div>
<p>Calculamos ahora <span class="math inline">\(\mathbf{A}\mathbf{v}_{i}\)</span> para <span class="math inline">\(i=1,2,3\)</span>:</p>
<p><span class="math display">\[
\begin{array}{lll}\mathbf{A} \mathbf{v}_{1} &amp;=&amp;\frac{1}{\sqrt{30} } \left( \begin{matrix}1&amp;0&amp;1\\ -2&amp;1&amp;0\end{matrix} \right)  \left( \begin{matrix}5\\ -2\\ 1\end{matrix} \right)  =\frac{1}{\sqrt{30} } \left( \begin{matrix}6\\ -12\end{matrix} \right)  =\left( \begin{matrix}6/\sqrt{30} \\ -12/\sqrt{30} \end{matrix} \right)  \\ \mathbf{A} \mathbf{v}_{2} &amp;=&amp;\frac{1}{\sqrt{5} } \left( \begin{matrix}1&amp;0&amp;1\\ -2&amp;1&amp;0\end{matrix} \right)  \left( \begin{matrix}0\\ 1\\ 2\end{matrix} \right)  =\frac{1}{\sqrt{5} } \left( \begin{matrix}2\\ 1\end{matrix} \right)  =\left( \begin{matrix}2/\sqrt{5} \\ 1/\sqrt{5} \end{matrix} \right)  \\ \mathbf{A} \mathbf{v}_{3} &amp;=&amp;\frac{1}{\sqrt{6} } \left( \begin{matrix}1&amp;0&amp;1\\ -2&amp;1&amp;0\end{matrix} \right)  \left( \begin{matrix}-1\\ -2\\ 1\end{matrix} \right)  =\frac{1}{\sqrt{6} } \left( \begin{matrix}0\\ 0\end{matrix} \right)  =\left( \begin{matrix}0\\ 0\end{matrix} \right)  \end{array} \tag{7.48}
\]</span></p>
<p>Como hay dos valores singulares no nulos, calculamos</p>
<div class="eq-scroll">
<p><span class="math display">\[
\mathbf{u}_{1} =\frac{1}{\sigma_{1} } \mathbf{A} \mathbf{v}_{1} =\frac{1}{\sqrt{6} } \frac{1}{\sqrt{30} } \left( \begin{matrix}1&amp;0&amp;1\\ -2&amp;1&amp;0\end{matrix} \right)  \left( \begin{matrix}5\\ -2\\ 1\end{matrix} \right)  =\left( \begin{matrix}1/\sqrt{5} \\ -2/\sqrt{5} \end{matrix} \right)  \wedge \mathbf{u}_{2} =\frac{1}{\sigma_{2} } \mathbf{A} \mathbf{v}_{2} =\frac{1}{\sqrt{5} } \left( \begin{matrix}1&amp;0&amp;1\\ -2&amp;1&amp;0\end{matrix} \right)  \left( \begin{matrix}0\\ 1\\ 2\end{matrix} \right)  =\left( \begin{matrix}2/\sqrt{5} \\ 1/\sqrt{5} \end{matrix} \right) \tag{7.49}
\]</span></p>
</div>
<p>Notemos que <span class="math inline">\(\beta =\left\{ \mathbf{u}_{1} ,\mathbf{u}_{2} \right\}  =\left\{ \left( \begin{matrix}1/\sqrt{5} \\ -2/\sqrt{5} \end{matrix} \right)  ,\left( \begin{matrix}2/\sqrt{5} \\ 1/\sqrt{5} \end{matrix} \right)  \right\}\)</span> es una base ortonormal de <span class="math inline">\(\mathbb{R}^{2}\)</span>. Por lo tanto,</p>
<p><span class="math display">\[
\mathbf{A} =\underbrace{\left( \begin{array}{rr}\displaystyle \frac{1}{\sqrt{5} } &amp;\displaystyle \frac{2}{\sqrt{5} } \\ -\displaystyle \frac{2}{\sqrt{5} } &amp;\displaystyle \frac{1}{\sqrt{5} } \end{array} \right)  }_{\mathbf{U} } \underbrace{\left( \begin{matrix}\sqrt{6} &amp;0&amp;0\\ 0&amp;1&amp;0\end{matrix} \right)  }_{\mathbf{\Sigma } } \underbrace{\left( \begin{array}{rrr}\displaystyle \frac{5}{\sqrt{30} } &amp;0&amp;-\displaystyle \frac{1}{\sqrt{6} } \\ -\displaystyle \frac{2}{\sqrt{30} } &amp;\displaystyle \frac{1}{\sqrt{5} } &amp;-\displaystyle \frac{2}{\sqrt{6} } \\ \displaystyle \frac{1}{\sqrt{30} } &amp;\displaystyle \frac{2}{\sqrt{5} } &amp;\displaystyle \frac{1}{\sqrt{6} } \end{array} \right)  }_{\mathbf{V}^{\top } } \tag{7.50}
\]</span></p>
<p>es la descomposición en valores singulares buscada. ◼︎</p>
<p><strong>Ejemplo 7.7 – Implementación <em>high-level</em> de la descomposición SVD en <font color="darkmagenta">Numpy</font>:</strong> La librería <strong><font color="darkmagenta">Numpy</font></strong> nos provee con una implementación bastante eficiente de la descomposición en valores singulares por medio de su módulo <code>numpy.linalg</code>. Puntualmente, la función <code>svd()</code> permite obtener tal descomposición sobre cualquier arreglo bidimensional que represente una matriz.</p>
<p>Consideremos la matriz del ejemplo anterior:</p>
<div id="9a868c74" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Definimos la matriz A.</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.array([</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">1</span>],</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    [<span class="op">-</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">0</span>],</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La función <code>svd()</code> requiere como único argumento la matriz sobre la cual deseamos operar. Como resultado, se retorna una tupla con las matrices <code>U</code>, <code>S</code> y <code>V_t</code>, que representan las componentes de la descomposición propiamente tal. No obstante, debemos notar que <code>S</code> no es la matriz de diagonal <span class="math inline">\(\mathbf{\Sigma}\)</span> que se usa en la descomposición, sino un arreglo unidimensional donde se almacenan únicamente los valores singulares de <code>A</code>:</p>
<div id="4810bfac" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Obtenemos la descomposición en valores singulares de A.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>U, S, V_t <span class="op">=</span> np.linalg.svd(A)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Vectores singulares por la izquierda.</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>U.<span class="bu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="13">
<pre><code>array([[-0.447,  0.894],
       [ 0.894,  0.447]])</code></pre>
</div>
</div>
<div id="a0b74fa4" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vectores singulares por la derecha.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>V_t.<span class="bu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<pre><code>array([[-0.913,  0.365, -0.183],
       [-0.   ,  0.447,  0.894],
       [-0.408, -0.816,  0.408]])</code></pre>
</div>
</div>
<div id="dc727bba" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores singulares de A.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>S.<span class="bu">round</span>(<span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>array([2.449, 1.   ])</code></pre>
</div>
</div>
<div id="ceacb454" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Matriz de valores singulares.</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>E <span class="op">=</span> np.eye(M<span class="op">=</span>V_t.shape[<span class="dv">0</span>], N<span class="op">=</span>U.shape[<span class="dv">0</span>]) <span class="op">*</span> S.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Recorstruimos la matriz A a partir de la descomposición SVD.</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span>(U <span class="op">@</span> E <span class="op">@</span> V_t).<span class="bu">round</span>(<span class="dv">1</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Y la imprimimos en pantalla.</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>A</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>array([[ 1., -0.,  1.],
       [-2.,  1.,  0.]])</code></pre>
</div>
</div>
<p>Y ahí lo tenemos. Se trata de una implementación eficiente y muy útil en la construcción de modelos de alta complejidad y que, por supuesto, nos ahorra el enorme trabajo manual que habíamos hecho previamente. ◼︎</p>
</section>
</section>
<section id="aproximación-matricial." class="level2">
<h2 class="anchored" data-anchor-id="aproximación-matricial.">Aproximación matricial.</h2>
<p>Hemos considerado la descomposición en valores singulares como una forma de factorizar una matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span> en términos del producto entre tres matrices <span class="math inline">\(\mathbf{U}\in \mathbb{R}^{m\times m}\)</span>, <span class="math inline">\(\mathbf{\Sigma}\in \mathbb{R}^{m\times n}\)</span> y <span class="math inline">\(\mathbf{V}\in \mathbb{R}^{n\times n}\)</span>, donde <span class="math inline">\(\mathbf{U}\)</span> y <span class="math inline">\(\mathbf{V}\)</span> son matrices ortogonales y <span class="math inline">\(\mathbf{\Sigma}\)</span> contiene los valores singulares de <span class="math inline">\(\mathbf{A}\)</span> en su diagonal. En vez de realizar la descomposición SVD completa, ahora investigaremos cómo dicha descomposición nos permite representar una matriz <span class="math inline">\(\mathbf{A}\)</span> como una suma de matrices más simples (siendo “más simples” por tener un rango menor que el rango de <span class="math inline">\(\mathbf{A}\)</span>), el cual tiende a conformar un esquema de aproximación matricial que resulta mucho menos costoso de calcular que la descomposición SVD completa.</p>
<p>Podemos construir una matriz de rango 1, <span class="math inline">\(\mathbf{A}_{i}\in \mathbb{R}^{m\times n}\)</span> como</p>
<p><span class="math display">\[
\mathbf{A}_{i}=\mathbf{u}_{i} \mathbf{v}_{i}^{\top} \tag{7.51}
\]</span></p>
<p>La cual está conformada por el producto exterior entre el <span class="math inline">\(i\)</span>-ésimo vector columna de <span class="math inline">\(\mathbf{U}\)</span> con <span class="math inline">\(i\)</span>-ésimo vector columna de <span class="math inline">\(\mathbf{V}\)</span>.</p>
<p>La <a href="#fig-stonehenge" class="quarto-xref">Figure&nbsp;4</a> muestra una imagen de Stonehenge, la cual está constituida por una matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{1432\times 1910}\)</span> (bajo la etiqueta <em>“original image”</em>), donde cada elemento de la matriz representa un determinado pixel con una cierta intensidad (y que es, por supuesto, un número real). Usaremos esta imagen como ejemplo de lo que podemos hacer, en términos de la <strong>compresión de información</strong> y <strong>representatividad</strong>, utilizando como base la aproximación matricial aprovechando la descomposición en valores singulares.</p>
<div id="fig-stonehenge" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stonehenge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig_7_4.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stonehenge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Procesamiento de una imagen de Stonhenge por medio de una descomposición SVD; (a) La imagen original corresponde a una matriz <span class="math inline">\(\mathbf{A}\)</span> de 1432$$1910 pixeles, donde cada valor de la matriz es un número real <span class="math inline">\(a_{ij}\)</span> tal que <span class="math inline">\(0\leq a_{ij}\leq 1\)</span>, donde 0 representa un color totalmente negro, y 1 un color totalmente blanco. De (b) a (f) se muestran matrices de rango 1 a 5, <span class="math inline">\(\mathbf{A}_{1},...,\mathbf{A}_{5}\)</span>, y sus correspondientes valores singulares <span class="math inline">\(\sigma_{1},...,\sigma_{5}\)</span>. La estructura de tipo grilla de cada matriz de rango 1 en esta imagen queda definida por el producto exterior de los vectores singulares por la izquierda y por la derecha (<span class="math inline">\(\mathbf{U}\)</span> y <span class="math inline">\(\mathbf{V}\)</span>) (imagen tomada del fantástico libro “Mathematics for Machine Learning”, (Deinsenroth, M., Faisal, A. &amp; Soon Ong, C.; 2021))
</figcaption>
</figure>
</div>
<p>Una matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span> de rango <span class="math inline">\(r\)</span> puede ser escrita como una <strong>suma de matrices de rango 1</strong>, digamos <span class="math inline">\(\mathbf{A}_{i}\)</span>, de manera tal que</p>
<p><span class="math display">\[
\mathbf{A} =\sum^{r}_{i=1} \sigma_{i} \mathbf{u}_{i} \mathbf{v}^{\top }_{i} =\sum^{r}_{i=1} \sigma_{i} \mathbf{A}_{i} \tag{7.52}
\]</span></p>
<p>Donde las matrices <span class="math inline">\(\mathbf{A}_{i}\)</span> resultantes de los productos exteriores se ponderan por el <span class="math inline">\(i\)</span>-ésimo valor singular <span class="math inline">\(\sigma_{i}\)</span>. Podemos observar por qué se cumple la ecuación (7.52): La estructura diagonal de la matriz de valores singulares <span class="math inline">\(\mathbf{\Sigma}\)</span> multiplica únicamente los correspondientes vectores <span class="math inline">\(\mathbf{u}_{i}\mathbf{v}_{i}^{\top}\)</span> y los escala por los correspondientes valores singulares <span class="math inline">\(\sigma_{i}\)</span>. Todos los términos <span class="math inline">\(\sum\nolimits_{ij} \sigma_{i} \mathbf{u}_{i} \mathbf{v}^{\top }_{i}\)</span> se anulan para <span class="math inline">\(i\neq j\)</span>, porque <span class="math inline">\(\mathbf{\Sigma}\)</span> es una matriz diagonal. Cualquier término para el cual <span class="math inline">\(i&gt;r\)</span> también se anula, porque los correspondientes valores singulares son también nulos.</p>
<p>En la ecuación (7.51) introducimos las matrices de rango 1, denotadas como <span class="math inline">\(\mathbf{A}_{i}\)</span>. En este caso, sumamos hasta la <span class="math inline">\(r\)</span>-ésima matriz de rango 1 para obtener la matriz <span class="math inline">\(\mathbf{A}\)</span> de rango <span class="math inline">\(r\)</span>. Si la suma no se realiza sobre las <span class="math inline">\(r\)</span> matrices <span class="math inline">\(\mathbf{A}_{i}\)</span>, sino que hasta un valor <span class="math inline">\(k&lt;r\)</span>, obtenemos lo que llamamos una <strong>aproximación de rango <span class="math inline">\(k\)</span></strong> para la matriz <span class="math inline">\(\mathbf{A}\)</span>, y que denotamos como <span class="math inline">\(\widehat{\mathbf{A} } \left( k\right)\)</span>. Es decir,</p>
<p><span class="math display">\[
\widehat{\mathbf{A} } \left( k\right)  :=\sum^{k}_{i=1} \sigma_{i} \mathbf{u}_{i} \mathbf{v}^{\top }_{i} =\sum^{k}_{i=1} \sigma_{i} \mathbf{A}_{i} \tag{7.53}
\]</span></p>
<p>Donde <span class="math inline">\(\rho(\mathbf{A})=k\)</span>. La <a href="#fig-stonecompress" class="quarto-xref">Figure&nbsp;5</a> permite observar el efecto de las aproximaciones de bajo rango <span class="math inline">\(\widehat{\mathbf{A} } \left( k\right)\)</span> para la imagen original de Stonehenge representada, en este caso, por la matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{1432\times 1910}\)</span>. La forma de estas rocas se vuelve incrementalmente visible y claramente reconocible en la aproximación de rango <span class="math inline">\(k=5\)</span>. Mientras que la imagen original requiere un total de 1432 <span class="math inline">\(\times\)</span> 1910 = 2735120 vectores para su representación, la aproximación de rango 5 requiere almacenar únicamente 5 vectores singulares por la izquierda y por la derecha, respectivamente, conforme filas y columnas; es decir, un total de 5<span class="math inline">\(\times\)</span>(1432 + 1910 + 1) = 16715 números. Aproximadamente un 0.6% del total de valores necesarios en la matriz original.</p>
<div id="fig-stonecompress" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stonecompress-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/fig_7_5.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stonecompress-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: 5 aproximaciones de baja densidad para la matriz <span class="math inline">\(\mathbf{A}\)</span> que representa la imagen de Stonehenge (imagen tomada del fantástico libro “Mathematics for Machine Learning”, (Deinsenroth, M., Faisal, A. &amp; Soon Ong, C.; 2021))
</figcaption>
</figure>
</div>
<p>Tomémonos un tiempo para entender lo importante que fue lo anterior: Usando un 0.6% de la data original, podemos representar la imagen a un nivel tal que es posible reconocer la formación rocosa de Stonehenge sin mayores problemas. Con aproximaciones ligeramente de mayor densidad (digamos, un 10% de la data original), podemos <em>comprimir</em> la imagen sin perder demasiada información relevante, lo que es de extrema importancia en el contexto de los llamados <strong>modelos de reducción de dimensionalidad</strong>: Muchas veces, cuando disponemos de conjuntos de datos con demasiadas variables, muchas de ellas son <strong>redundantes</strong> o, en realidad, comunican <strong>poca información</strong>.</p>
<p>Para medir la diferencia (error) entre <span class="math inline">\(\mathbf{A}\)</span> y su aproximación de rango <span class="math inline">\(k\)</span>, podemos utilizar un tipo particular de norma de matrices, que requiere de una definición particular.</p>
<p><strong><font color="blue">Definición 7.2 – Norma espectral de una matriz:</font></strong> Para <span class="math inline">\(\mathbf{x} \in \mathbb{R}^{n} -\left\{ \mathbf{0} \right\}\)</span>, definimos la <strong>norma espectral</strong> de la matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span> como</p>
<p><span class="math display">\[
\left\Vert \mathbf{A} \right\Vert_{2}  :=\max_{\mathbf{x} } \left( \frac{\left\Vert \mathbf{A} \mathbf{x} \right\Vert_{2}  }{\left\Vert \mathbf{x} \right\Vert_{2}  } \right)  =\sqrt{\max_{j} \left( \lambda_{j} \right)  \mathbf{A}^{\top } \mathbf{A} } \tag{7.54}
\]</span></p>
<p>Donde <span class="math inline">\(\max_{j} \left( \lambda_{j} \right)\)</span> hace referencia al mayor de los autovalores de <span class="math inline">\(\mathbf{A}\)</span>. De esta manera, la norma espectral de una matriz nos permite entender qué tan largo puede hacerse un vector, como máximo, cuando lo multiplicamos por la matriz <span class="math inline">\(\mathbf{A}\)</span>.</p>
<p>La definición (7.2) motiva los siguientes teoremas.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Teorema 7.4
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>La norma espectral de una matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span> es igual a su valor singular de mayor magnitud.</em></p>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Teorema 7.5 – Eckart-Young
</div>
</div>
<div class="callout-body-container callout-body">
<p><em>Consideremos la matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span> de rango <span class="math inline">\(\rho(\mathbf{A})=r\)</span>, y sea <span class="math inline">\(\mathbf{B}\in \mathbb{R}^{m\times n}\)</span> otra matriz de rango <span class="math inline">\(\rho(\mathbf{B})=k\)</span>. Entonces, para todo <span class="math inline">\(k\neq r\)</span>, con <span class="math inline">\(\widehat{\mathbf{A} } \left( k\right)  =\sum\nolimits^{k}_{i=1} \sigma_{i} \mathbf{u}_{i} \mathbf{v}^{\top }_{i}\)</span>, se tiene que</em></p>
<p><span class="math display">\[
\widehat{\mathbf{A} } \left( k\right)  =\mathrm{argmin}_{\rho \left( \mathbf{B} \right)  =k} \left\Vert \mathbf{A} -\mathbf{B} \right\Vert_{2}  \  ;\  \left\Vert \mathbf{A} -\widehat{\mathbf{A} } \left( k\right)  \right\Vert_{2}  =\sigma_{k+1} \tag{7.55}
\]</span></p>
</div>
</div>
<p>El teorema (7.5) establece de manera explícita cuánto error inducimos al aproximar <span class="math inline">\(\mathbf{A}\)</span> por medio de <span class="math inline">\(\widehat{\mathbf{A}}(k)\)</span>. Podemos interpretar la aproximación de rango <span class="math inline">\(k\)</span> obtenida mediante la descomposición en valores singulares como una proyección de la matriz completa <span class="math inline">\(\mathbf{A}\)</span> sobre un espacio de menor dimensión que el dominio de <span class="math inline">\(\mathbf{A}\)</span>. De todas las posibles proyecciones, la obtenida mediante una descomposición SVD minimiza el error (con respecto a la norma espectral) entre <span class="math inline">\(\mathbf{A}\)</span> y cualquier aproximación de rango <span class="math inline">\(k\)</span>.</p>
<p>Vamos a demostrar el teorema (7.5) a fin de comprender un poco el por qué se cumple para toda matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{m\times n}\)</span>. Supongamos entonces que <span class="math inline">\(\mathbf{A} =\mathbf{U} \mathbf{\Sigma } \mathbf{V}^{\top }\)</span> es la descomposición en valores singulares de <span class="math inline">\(\mathbf{A}\)</span>. Recordemos que <span class="math inline">\(\mathbf{U}\)</span> y <span class="math inline">\(\mathbf{V}\)</span> son matrices ortogonales y <span class="math inline">\(\mathbf{\Sigma}\)</span> es una matriz diagonal de las mismas dimensiones que <span class="math inline">\(\mathbf{A}\)</span>, con entradas no nulas <span class="math inline">\(\sigma_{1},...,\sigma_{r}\)</span> tales que <span class="math inline">\(\sigma_{1}\geq \sigma_{2}\geq \cdots \geq \sigma_{r}\geq 0\)</span>. Hemos establecido previamente que la mejor aproximación para <span class="math inline">\(\mathbf{A}\)</span> de rango <span class="math inline">\(k\)</span>, conforme la norma espectral, es la mostrada en la ecuación (7.53). En este caso, de la ecuación (7.55), notamos que, usando propiedades de las sumatorias,</p>
<p><span class="math display">\[
\begin{array}{lll}\left\Vert \mathbf{A} -\widehat{\mathbf{A} } \left( k\right)  \right\Vert_{2}  &amp;=&amp;\left\Vert \sum^{n}_{i=1} \sigma_{i} \mathbf{u}_{i} \mathbf{v}^{\top }_{i} -\sum^{k}_{i=1} \sigma_{i} \mathbf{u}_{i} \mathbf{v}^{\top }_{i} \right\Vert  \\ &amp;=&amp;\left\Vert \sum^{n}_{i=k+1} \sigma_{i} \mathbf{u}_{i} \mathbf{v}^{\top }_{i} \right\Vert  \\ &amp;=&amp;\sigma_{k+1} \end{array} \tag{7.56}
\]</span></p>
<p>Por lo tanto, necesitamos mostrar que, si <span class="math inline">\(\widehat{\mathbf{B} } \left( k\right)  =\mathbf{X} \mathbf{Y}^{\top }\)</span>, donde <span class="math inline">\(\mathbf{X}\)</span> e <span class="math inline">\(\mathbf{Y}\)</span> tienen <span class="math inline">\(k\)</span> columnas, entonces <span class="math inline">\(\left\Vert \mathbf{A} -\widehat{\mathbf{A} } \left( k\right)  \right\Vert_{2}  =\sigma_{k+1} \leq \left\Vert \mathbf{A} -\widehat{\mathbf{B} } \left( k\right)  \right\Vert_{2}\)</span>.</p>
<p>Ya que <span class="math inline">\(\mathbf{Y}\)</span> tiene <span class="math inline">\(k\)</span> columnas, entondes debe existir una combinación lineal no trivial de las primeras <span class="math inline">\(k+1\)</span> columnas de <span class="math inline">\(\mathbf{V}\)</span>. Es decir,</p>
<p><span class="math display">\[
\mathbf{w} =\gamma_{1} \mathbf{v}_{1} +\cdots +\gamma_{k+1} \mathbf{v}_{k+1} \tag{7.57}
\]</span></p>
<p>tal que <span class="math inline">\(\mathbf{Y}^{\top}\mathbf{w}=0\)</span>. Sin pérdida de generalidad, podemos escalar <span class="math inline">\(\mathbf{w}\)</span> de manera tal que <span class="math inline">\(\left\Vert \mathbf{w} \right\Vert_{2}  =1\)</span> o, equivalentemente, <span class="math inline">\(\gamma_{1}^{2}+\cdots +\gamma_{k+1}^{2}=1\)</span>. Por lo tanto,</p>
<p><span class="math display">\[
\left\Vert \mathbf{A} -\widehat{\mathbf{B} } \left( k\right)  \right\Vert^{2}_{2}  \geq \left\Vert \left( \mathbf{A} -\widehat{\mathbf{B} } \left( k\right)  \right)  \mathbf{w} \right\Vert^{2}_{2}  =\left\Vert \mathbf{A} \mathbf{w} \right\Vert^{2}_{2}  =\sum^{k+1}_{i=1} \gamma^{2}_{i} \sigma^{2}_{i} \geq \sigma^{2}_{k+1} \tag{7.58}
\]</span></p>
<p>El teorema (7.5) queda finalmente demostrado tomando raíces cuadradas a ambos lados de la desigualdad.</p>
<p>El teorema de Eckart-Young implica que podemos utilizar la descomposición SVD para reducir una matriz matriz de rango <span class="math inline">\(r\)</span>, digamos <span class="math inline">\(\mathbf{A}\)</span>, a una matriz de rango <span class="math inline">\(k\)</span>, digamos <span class="math inline">\(\widehat{\mathbf{A}}\)</span>, en términos óptimos (desde la perspectiva de la norma espectral). Podemos interpretar una aproximación de este tipo como una especie de compresión con cierto nivel de pérdida de información. Por lo tanto, la aproximación de rango bajo de una matriz aparece en muchísimas aplicaciones típicas en machine learning, tales como <strong>filtros de ruido, procesamiento de imágenes y regularización</strong> en ciertos problemas. Además, juega un rol fundamental en el problema de <strong>reducción de dimensionalidad</strong> que revisaremos más adelante, al abordar los <strong>algoritmos de aprendizaje no supervisado</strong>.</p>
<p><strong>Ejemplo 7.8:</strong> La descomposición en valores singulares es una técnica muy utilizada en machine learning para construir modelos que permitan reducir el número de variables que representan cierta información en un conjunto de datos, sin perder demasiada de esa información (es decir, preservando una fracción importante de la varianza del conjunto de datos original). Tal enfoque es conocido en la práctica como <strong>reducción de dimensionalidad</strong>, y constituye la base de una serie de modelos conocidos como modelos de aprendizaje no supervisado.</p>
<p>En el contexto de las imágenes, la reducción de dimensionalidad implica <strong>representar la misma imagen mediante una menor cantidad de datos</strong>, lo que suele traducirse en menor resolución. La descomposición en valores singulares nos permite determinar cuál es el orden de compresión máximo que podemos lograr y que preserve la misma imagen que podemos ver originalmente.</p>
<p>Para ejemplificar lo anterior, trabajaremos nuestra imagen del camión con cero emisiones. Para ello, haremos uso de la librería <strong><font color="darkmagenta">Scikit-Image</font></strong>, especializada en el trabajo con imágenes, pero únicamente para acceder a la imagen de nuestro camión vía escala de grises, a fin de evitar procesar información innecesaria (los canales de color). Por supuesto, también haremos uso de <strong><font color="darkmagenta">Matplotlib</font></strong> para manipular imágenes:</p>
<div id="56d78a4f" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="79f8032a" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> skimage <span class="im">import</span> io</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="98e62971" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Preseteamos algunos parámetros para obtener imágenes bien bonitas.</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>plt.rcParams[<span class="st">"figure.dpi"</span>] <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>plt.style.use(<span class="st">"seaborn-v0_8-white"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="97cc9ca6" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Vamos a hacer uso de una imagen del primer camión de extracción (CAEX) diseñado para su plena operación gracias a un sistema de propulsión híbrido proporcionado por una batería de hidrógeno (H2) de 2000 kW, con mayor capacidad de generación de energía que su símil propulsado por diesel. Esta imagen se encuentra disponible en la localización <code>datasets/caex.jpeg</code>:</p>
<div id="45e1e080" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accedemos a la imagen.</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>img <span class="op">=</span> io.imread(<span class="st">"./datasets/caex.jpeg"</span>, as_gray<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>La imagen de nuestro camión, en términos matemáticos, no es más que un arreglo muy grande de números que representan la intensidad de cada pixel que conforma la foto completa. De hecho, si chequeamos la geometría del arreglo que representa a esta imagen, obtenemos:</p>
<div id="12170dd1" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Morfología de la imagen del CAEX.</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>img.shape</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<pre><code>(2832, 3776)</code></pre>
</div>
</div>
<p>Es decir, la imagen almacenada en la variable <code>img</code> corresponde a una matriz <span class="math inline">\(\mathbf{A}\in \mathbb{R}^{2832\times 3776}\)</span>:</p>
<div id="d8792c20" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostramos la imagen del CAEX.</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>plt.imshow(img, cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">False</span>)</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">"off"</span>)<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-24-output-1.png" width="794" height="601" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Vamos a utilizar la función <code>svd()</code>, como hicimos previamente, para obtener una descomposición en valores singulares a fin de construir aproximaciones matriciales de la imagen de nuestro CAEX de rango <span class="math inline">\(k=5, 10, 25, 50\)</span>, a fin de observar cómo se ve afectada la <strong>representatividad</strong> de la imagen al comprimirse por medio de tales aproximaciones. Luego tenemos:</p>
<div id="826d8a00" class="cell" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Descomposición en valores singulares de la imagen.</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>U, S, V_t <span class="op">=</span> np.linalg.svd(img)</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Inicializamos algunas listas vacías para almacenar las componentes de las aproximaciones.</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>U_vals, S_vals, V_t_vals <span class="op">=</span> [], [], []</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>compressed_imgs <span class="op">=</span> []</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Y ahora construimos las aproximaciones correspondientes (de rango k).</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> [<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">25</span>, <span class="dv">50</span>]:</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>    U_k <span class="op">=</span> U[:, :k] <span class="co"># Aproximación de rango k para U.</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>    S_k <span class="op">=</span> np.diag(S[:k]) <span class="co"># Valores singulares de la aproximación.</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>    V_t_k <span class="op">=</span> V_t[:k] <span class="co"># Aproximación de rango k para V.</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Almacenamos estas aproximaciones en las listas correspondientes.</span></span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a>    U_vals.append(U_k)</span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a>    S_vals.append(S_k)</span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a>    V_t_vals.append(V_t_k)</span>
<span id="cb38-18"><a href="#cb38-18" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb38-19"><a href="#cb38-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Aproximación de rango k para la imagen completa.</span></span>
<span id="cb38-20"><a href="#cb38-20" aria-hidden="true" tabindex="-1"></a>    rank_k_approximation <span class="op">=</span> U_k <span class="op">@</span> S_k <span class="op">@</span> V_t_k</span>
<span id="cb38-21"><a href="#cb38-21" aria-hidden="true" tabindex="-1"></a>    compressed_imgs.append(rank_k_approximation)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Ahora graficamos las aproximaciones construidas y observamos con atención los resultados:</p>
<div id="210e2fd9" class="cell" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>), nrows<span class="op">=</span><span class="dv">2</span>, ncols<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>, <span class="dv">0</span>].imshow(compressed_imgs[<span class="dv">0</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>, <span class="dv">0</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>, <span class="dv">0</span>].set_title(</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="vs">r"Reconstrucción vía SVD con </span><span class="dv">$</span><span class="vs">k=4</span><span class="dv">$</span><span class="vs">"</span>, </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">12</span>, </span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>, <span class="dv">1</span>].imshow(compressed_imgs[<span class="dv">1</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>, <span class="dv">1</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>, <span class="dv">1</span>].set_title(</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    <span class="vs">r"Reconstrucción vía SVD con </span><span class="dv">$</span><span class="vs">k=10</span><span class="dv">$</span><span class="vs">"</span>, </span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">12</span>, </span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>, <span class="dv">0</span>].imshow(compressed_imgs[<span class="dv">2</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>, <span class="dv">0</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>, <span class="dv">0</span>].set_title(</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>    <span class="vs">r"Reconstrucción vía SVD con </span><span class="dv">$</span><span class="vs">k=25</span><span class="dv">$</span><span class="vs">"</span>, </span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">12</span>, </span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>, <span class="dv">1</span>].imshow(compressed_imgs[<span class="dv">3</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>, <span class="dv">1</span>].axis(<span class="st">"off"</span>)</span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>, <span class="dv">1</span>].set_title(</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>    <span class="vs">r"Reconstrucción vía SVD con </span><span class="dv">$</span><span class="vs">k=50</span><span class="dv">$</span><span class="vs">"</span>, </span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">12</span>, </span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()<span class="op">;</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-26-output-1.png" width="989" height="859" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Notemos que el rango de la matriz original es:</p>
<div id="d63efec6" class="cell" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rango de la matriz original.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>np.linalg.matrix_rank(img)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="26">
<pre><code>np.int64(2832)</code></pre>
</div>
</div>
<p>Basta, por tanto, una aproximación de rango 50 para preservar, al menos visualmente, una cantidad generosa de información para ver claramente nuestro camión. Esa es una enorme reducción de dimensionalidad de la matriz con la que hemos trabajado, ya que hemos representado a nuestro CAEX sin dar lugar a confusión con menos del 2% de los datos originales, lo que es una compresión gigantesca sin perder una cantidad significativa de información. ◼</p>
</section>
<section id="comentarios-finales." class="level2">
<h2 class="anchored" data-anchor-id="comentarios-finales.">Comentarios finales.</h2>
<p>Con este apunte cerramos un ciclo importante dentro del estudio de las <strong>estructuras lineales</strong>. A lo largo de esta serie de apuntea hemos pasado desde los conceptos más elementales de espacio vectorial, base y transformación lineal, hacia herramientas mucho más profundas que permiten <strong>entender, reorganizar y simplificar</strong> la información contenida en una matriz. Las descomposiciones matriciales representan, en este sentido, una culminación natural del camino recorrido. Muestran que una matriz no debe verse únicamente como un arreglo de números, sino como un objeto estructurado que puede factorizarse en piezas con significado algebraico, geométrico y computacional.</p>
<p>La factorización de <strong>Cholesky</strong> nos mostró que, bajo hipótesis adecuadas de simetría y positividad, una matriz puede descomponerse en un producto especialmente conveniente para el cálculo numérico. La descomposición <strong>QR</strong>, por su parte, profundizó la conexión entre ortogonalidad, proyecciones y estabilidad computacional, haciendo visible el papel central que juegan las bases ortonormales en problemas de aproximación. Finalmente, la descomposición en <strong>valores singulares</strong> nos permitió ir todavía más lejos. Ya no sólo descomponer matrices cuadradas bien comportadas, sino <strong>cualquier matriz</strong>, incluso rectangular, en términos de cambios de base ortogonales y escalamientos bien controlados.</p>
<p>Desde el punto de vista geométrico, estas descomposiciones refuerzan una idea que ha aparecido repetidamente en estos apuntes. Y es que muchas transformaciones lineales pueden entenderse como combinaciones de <strong>rotaciones, reflexiones, proyecciones, escalamientos y cambios de coordenadas</strong>. Lo notable es que estas operaciones no son solamente intuiciones geométricas; son mecanismos algebraicos precisos que permiten diseñar algoritmos robustos, interpretar datos y construir aproximaciones óptimas.</p>
<p>Desde el punto de vista computacional, este apunte también deja una enseñanza importante: En problemas reales, rara vez conviene trabajar de manera ingenua con una matriz “tal cual es”. En cambio, suele ser muchísimo más útil buscar una representación equivalente o aproximada que sea más fácil de manipular, más estable numéricamente o más económica en almacenamiento. Allí reside buena parte de la importancia práctica de las descomposiciones matriciales en estadística, optimización, procesamiento de señales, visión computacional y aprendizaje automático.</p>
<p>En particular, la descomposición SVD entrega uno de los mensajes más poderosos de todo el curso hasta ahora: Una matriz grande y aparentemente compleja puede contener, en realidad, una estructura dominante de muy baja dimensión. Esto explica por qué la compresión de información, la reducción de dimensionalidad y muchos modelos de aprendizaje no supervisado funcionan tan bien en la práctica: gran parte de la información relevante suele estar concentrada en unas pocas direcciones principales.</p>
<p>Con esto, la teoría de estructuras lineales queda suficientemente consolidada como para dar paso a una nueva etapa. Ya contamos con el lenguaje de espacios vectoriales, dualidad, productos internos, formas, espectro y descomposición. Todo ello nos permitirá abordar en adelante problemas más ricos, donde el énfasis ya no estará sólo en representar objetos lineales, sino también en estudiar cómo ciertas expresiones algebraicas describen geometría, curvatura, energía, optimización y modelos matemáticos más generales.</p>
<p>En un sentido más amplio, este apunte cierra la parte dedicada a estructuras lineales mostrando que el álgebra lineal no consiste únicamente en resolver sistemas o manipular arreglos matriciales, sino en <strong>descubrir estructuras inherentes a nuestros datos</strong>. Factorizar una matriz es, en el fondo, entender mejor la transformación que representa.</p>
<p>Así, concluimos esta primera gran parte del curso con una visión más madura del objeto central que ha acompañado todo nuestro recorrido: La matriz. Ya no la vemos sólo como una tabla de coeficientes, sino como una representación de operadores, geometrías, formas y mecanismos de compresión. Esa perspectiva será decisiva para todo lo que aprendamos en relación al aprendizaje automático.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© René Quezada</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Hecho con Quarto</p>
</div>
  </div>
</footer>




<script src="../../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>